# -*- coding: utf-8 -*-
# Croatian layer. Tuples are (english word, croatian word, easy hint, vague hint).
# The english word is the join key against the source list, so difficulty tags,
# ordering and category ids stay in sync automatically.

HR1 = {
    "food": ("Hrana", [
        ("Pizza", "Pizza", "Talijanska hrana", "Okrugla i dijeli se"),
        ("Burger", "Burger", "Brza hrana", "Slaže se u slojevima"),
        ("Ice Cream", "Sladoled", "Hladan desert", "Otopi se ako čekaš"),
        ("Pasta", "Tjestenina", "Talijanska hrana", "Prokuha pa se prelije"),
        ("Chocolate", "Čokolada", "Slatkiš", "Smeđa i primamljiva"),
        ("Sandwich", "Sendvič", "Hrana za ručak", "Dvije kriške i sredina"),
        ("Popcorn", "Kokice", "Grickalica u kinu", "Pucaju"),
        ("Sushi", "Sushi", "Japanska hrana", "Zamotano i sirovo"),
        ("Pancakes", "Palačinke", "Doručak", "Tanke i punjene"),
        ("French Fries", "Pomfrit", "Prilog uz brzu hranu", "Zlatni štapići"),
        ("Cheese", "Sir", "Mliječni proizvod", "Bolji kad odstoji"),
        ("Soup", "Juha", "Topli obrok", "Jede se žlicom"),
        ("Tacos", "Tacos", "Meksička hrana", "Presavijeno i punjeno"),
        ("Pancake Syrup", "Javorov sirup", "Preljev za doručak", "Spor i sladak"),
        ("Lasagna", "Lazanje", "Talijanska hrana", "Građeno u slojevima"),
        ("Donut", "Donut", "Slatka grickalica", "Ima rupu u sredini"),
        ("Cereal", "Pahuljice", "Doručak", "Traže mlijeko"),
        ("Barbecue", "Roštilj", "Kuha se vani", "Dim i vatra"),
        ("Curry", "Curry", "Začinjeno jelo", "Toplo i šareno"),
        ("Salad", "Salata", "Zdravo jelo", "Uglavnom zeleno"),
        ("Croissant", "Croissant", "Francusko pecivo", "Savijeno i lisnato"),
        ("Pretzel", "Perec", "Slana grickalica", "Uvijen"),
        ("Waffle", "Vafl", "Doručak", "Puno kvadratića"),
        ("Cheesecake", "Cheesecake", "Desert", "Bogat i ohlađen"),
        ("Ramen", "Ramen", "Japanska hrana", "Srče se iz zdjele"),
        ("Guacamole", "Guacamole", "Meksički umak", "Zeleno i zgnječeno"),
        ("Paella", "Paella", "Španjolska hrana", "Jedna velika tava"),
        ("Tiramisu", "Tiramisu", "Talijanski desert", "Kava i krema"),
        ("Hummus", "Humus", "Namaz", "Bež i kremast"),
        ("Pad Thai", "Pad Thai", "Jelo s rezancima iz Azije", "Kupljeno na uličnoj tezgi"),
        ("Baklava", "Baklava", "Slatko pecivo", "Ljepljivo i u slojevima"),
        ("Kebab", "Kebab", "Ulična hrana", "Skinuto s ražnja"),
    ]),

    "sports": ("Sport", [
        ("Football", "Nogomet", "Sport s loptom", "Jedanaest po strani"),
        ("Basketball", "Košarka", "Sport s loptom", "Ciljaj visoko"),
        ("Tennis", "Tenis", "Sport s reketom", "Amo-tamo"),
        ("Swimming", "Plivanje", "Vodeni sport", "Staza po staza"),
        ("Running", "Trčanje", "Atletska disciplina", "Noga pred nogu"),
        ("Boxing", "Boks", "Borilački sport", "Dvoje u kvadratu"),
        ("Cycling", "Biciklizam", "Sport na kotačima", "Dva kruga se vrte"),
        ("Volleyball", "Odbojka", "Sport s loptom", "Preko mreže"),
        ("Golf", "Golf", "Sport sa štapovima", "Vrlo mala meta"),
        ("Skiing", "Skijanje", "Zimski sport", "Nizbrdo po hladnoći"),
        ("Baseball", "Bejzbol", "Američki sport", "Zamahni pa trči"),
        ("Ice Hockey", "Hokej na ledu", "Zimski momčadski sport", "Brzo i smrznuto"),
        ("Table Tennis", "Stolni tenis", "Dvoranski sport s reketom", "Sitno i brzo"),
        ("Surfing", "Surfanje", "Vodeni sport", "Čekaš pravi trenutak"),
        ("Gymnastics", "Gimnastika", "Olimpijski sport", "Ravnoteža i let"),
        ("Wrestling", "Hrvanje", "Borilački sport", "Bliski kontakt"),
        ("Rugby", "Ragbi", "Momčadski kontaktni sport", "Dodaje se unatrag"),
        ("Skateboarding", "Skateboarding", "Ulični sport", "Četiri mala kotača"),
        ("Marathon", "Maraton", "Trkaća disciplina", "Vrlo dugo"),
        ("Archery", "Streličarstvo", "Gađanje u metu", "Mirne ruke"),
        ("Formula 1", "Formula 1", "Motosport", "Vrlo bučni krugovi"),
        ("Bowling", "Kuglanje", "Dvoranski sport", "Sruši ih sve"),
        ("Climbing", "Penjanje", "Sport na otvorenom", "Samo prema gore"),
        ("Fencing", "Mačevanje", "Borilački sport", "Pristojan dvoboj"),
        ("Handball", "Rukomet", "Momčadski sport", "Baci, ne šutiraj"),
        ("Water Polo", "Vaterpolo", "Sport u bazenu", "Naporno i mokro"),
        ("Curling", "Curling", "Zimski sport", "Metenje po ledu"),
        ("Badminton", "Badminton", "Sport s reketom", "Perje u zraku"),
        ("Triathlon", "Triatlon", "Višesportska utrka", "Tri zaredom"),
        ("Snowboarding", "Snowboarding", "Zimski sport", "Bočno nizbrdo"),
    ]),

    "objects": ("Svakodnevni predmeti", [
        ("Toothbrush", "Četkica za zube", "Predmet iz kupaonice", "Dvaput dnevno"),
        ("Umbrella", "Kišobran", "Koristi se po lošem vremenu", "Otvara se iznad tebe"),
        ("Pillow", "Jastuk", "Nalazi se u spavaćoj sobi", "Mekan i tih"),
        ("Mirror", "Ogledalo", "Nalazi se u kupaonici", "Ne daje ništa svoje"),
        ("Keys", "Ključevi", "Nosi se u džepu", "Mali ali važni"),
        ("Chair", "Stolica", "Komad namještaja", "Koristiš je sjedeći"),
        ("Clock", "Sat", "Nešto ti govori", "Nikad ne staje"),
        ("Backpack", "Ruksak", "Nešto što nosiš", "Naramenice preko oba ramena"),
        ("Towel", "Ručnik", "Predmet iz kupaonice", "Namjerno se smoči"),
        ("Scissors", "Škare", "Alat za rezanje", "Dvije oštrice, jedan posao"),
        ("Candle", "Svijeća", "Daje svjetlo", "S vremenom sve kraća"),
        ("Wallet", "Novčanik", "Nosi se u džepu", "Drži važne kartice"),
        ("Broom", "Metla", "Alat za čišćenje", "Otjera prašinu"),
        ("Ladder", "Ljestve", "Kućni alat", "Pomažu ti dosegnuti"),
        ("Sunglasses", "Sunčane naočale", "Nosi se na licu", "Za svijetle dane"),
        ("Blanket", "Deka", "Nalazi se u spavaćoj sobi", "Topla i teška"),
        ("Toaster", "Toster", "Kuhinjski uređaj", "Iskoči"),
        ("Vacuum Cleaner", "Usisavač", "Uređaj za čišćenje", "Glasan i gladan"),
        ("Hairdryer", "Sušilo za kosu", "Uređaj u kupaonici", "Topli vjetar"),
        ("Doorbell", "Zvono na vratima", "Nalazi se na ulazu", "Najavljuje nekoga"),
        ("Stapler", "Klamerica", "Uredski predmet", "Drži papire zajedno"),
        ("Suitcase", "Kovčeg", "Koristi se na putovanju", "Spakiran i na kotačima"),
        ("Flashlight", "Baterijska svjetiljka", "Koristi se u mraku", "Samo kad zatreba"),
        ("Corkscrew", "Vadičep", "Kuhinjski alat", "Zavrne pa otvori"),
        ("Thermometer", "Toplomjer", "Mjerni instrument", "Kaže ti broj"),
        ("Fire Extinguisher", "Vatrogasni aparat", "Sigurnosna oprema", "Nadamo se da nikad"),
        ("Tape Measure", "Metar", "Mjerni instrument", "Sam se namota"),
        ("Nail Clippers", "Grickalica za nokte", "Pribor za njegu", "Mala i oštra"),
        ("Ironing Board", "Daska za glačanje", "Predmet za rublje", "Sklapa se"),
        ("Watering Can", "Kanta za zalijevanje", "Vrtni predmet", "Nježna kiša"),
    ]),

    "movies": ("Popularni filmovi", [
        ("Titanic", "Titanic", "Poznati film", "Završava pod vodom"),
        ("Frozen", "Snježno kraljevstvo", "Animirani film", "Vrlo hladno i vrlo pjevno"),
        ("Jurassic Park", "Jurski park", "Poznati film", "Vrlo stare životinje"),
        ("The Lion King", "Kralj lavova", "Animirani film", "Mladi vladar"),
        ("Harry Potter", "Harry Potter", "Fantastični film", "Škola s tajnom"),
        ("Avatar", "Avatar", "Znanstvenofantastični film", "Plavi i visoki"),
        ("Toy Story", "Priča o igračkama", "Animirani film", "Kreću se kad odeš"),
        ("Shrek", "Shrek", "Animirani film", "Zelen i mrzovoljan"),
        ("Finding Nemo", "Potraga za Nemom", "Animirani film", "Dugo plivanje"),
        ("Star Wars", "Ratovi zvijezda", "Znanstvenofantastični film", "Obiteljska drama u svemiru"),
        ("The Godfather", "Kum", "Klasični film", "Obiteljski posao"),
        ("Jaws", "Ralje", "Triler", "Ne idi u vodu"),
        ("Forrest Gump", "Forrest Gump", "Klasični film", "Vrlo dugo trčanje"),
        ("The Matrix", "Matrix", "Znanstvenofantastični film", "Odaberi boju"),
        ("Inception", "Početak", "Znanstvenofantastični film", "San je kompliciran"),
        ("Rocky", "Rocky", "Sportski film", "Stube i rukavice"),
        ("Home Alone", "Sam u kući", "Blagdanski film", "Namjerno zaboravljen"),
        ("Pirates of the Caribbean", "Pirati s Kariba", "Pustolovni film", "More i zlato"),
        ("Despicable Me", "Kako je Gru ukrao Mjesec", "Animirani film", "Mali žuti pomoćnici"),
        ("The Avengers", "Osvetnici", "Superjunački film", "Previše glavnih likova"),
        ("Back to the Future", "Povratak u budućnost", "Znanstvenofantastični film", "Vrlo brz automobil"),
        ("Gladiator", "Gladijator", "Povijesni film", "Pijesak i mačevi"),
        ("Interstellar", "Interstellar", "Znanstvenofantastični film", "Vrijeme je skupo"),
        ("Pulp Fiction", "Pakleni šund", "Kultni film", "Ispričano izvan reda"),
        ("The Shining", "Isijavanje", "Horor", "Vrlo tihi hotel"),
        ("Casablanca", "Casablanca", "Klasični film", "Crno-bijeli oproštaj"),
        ("Parasite", "Parazit", "Nagrađivani film", "Dva kućanstva"),
        ("La La Land", "La La Land", "Mjuzikl", "Ples i razočaranje"),
        ("Fight Club", "Klub boraca", "Kultni film", "Ne govori o tome"),
        ("Up", "Nebeske avanture", "Animirani film", "Baloni i kuća"),
    ]),

    "people": ("Poznate osobe", [
        ("Albert Einstein", "Albert Einstein", "Poznati znanstvenik", "Kosa i jednadžbe"),
        ("Michael Jackson", "Michael Jackson", "Poznati pjevač", "Jedna rukavica"),
        ("Leonardo da Vinci", "Leonardo da Vinci", "Poznati umjetnik", "Slikar i izumitelj"),
        ("Charlie Chaplin", "Charlie Chaplin", "Poznati glumac", "Tih i smiješan"),
        ("Cleopatra", "Kleopatra", "Povijesna vladarica", "Drevno kraljevstvo"),
        ("William Shakespeare", "William Shakespeare", "Poznati pisac", "Stara engleska drama"),
        ("Elvis Presley", "Elvis Presley", "Poznati pjevač", "Bokovi"),
        ("Marilyn Monroe", "Marilyn Monroe", "Poznata glumica", "Bijela haljina"),
        ("Nelson Mandela", "Nelson Mandela", "Poznati vođa", "Zatvor pa predsjedništvo"),
        ("Steve Jobs", "Steve Jobs", "Poznati poduzetnik", "Crna dolčevita"),
        ("Isaac Newton", "Isaac Newton", "Poznati znanstvenik", "Nešto je palo"),
        ("Marie Curie", "Marie Curie", "Poznata znanstvenica", "Sjajno istraživanje"),
        ("Napoleon", "Napoleon", "Povijesni vođa", "Nizak i ambiciozan"),
        ("Mozart", "Mozart", "Poznati skladatelj", "Počeo vrlo mlad"),
        ("Vincent van Gogh", "Vincent van Gogh", "Poznati slikar", "Zvijezde i jedno uho"),
        ("Walt Disney", "Walt Disney", "Poznati stvaratelj", "Sagradio kraljevstvo"),
        ("Oprah Winfrey", "Oprah Winfrey", "Poznata voditeljica", "Svi dobivaju auto"),
        ("Beyonce", "Beyoncé", "Poznata pjevačica", "Formacija"),
        ("Julius Caesar", "Julije Cezar", "Povijesni vođa", "Izdali ga prijatelji"),
        ("Bill Gates", "Bill Gates", "Poznati poduzetnik", "Prozori"),
        ("Frida Kahlo", "Frida Kahlo", "Poznata slikarica", "Autoportreti"),
        ("Galileo", "Galileo", "Poznati znanstvenik", "Pogledao gore i stradao"),
        ("Amelia Earhart", "Amelia Earhart", "Poznata pilotkinja", "Nikad nije sletjela"),
        ("Pablo Picasso", "Pablo Picasso", "Poznati slikar", "Lica s dvije strane"),
        ("Mahatma Gandhi", "Mahatma Gandhi", "Poznati vođa", "Pobijedio bez borbe"),
        ("Ludwig van Beethoven", "Ludwig van Beethoven", "Poznati skladatelj", "Nije čuo kraj"),
        ("Salvador Dali", "Salvador Dalí", "Poznati slikar", "Otopljeno vrijeme"),
        ("Alfred Hitchcock", "Alfred Hitchcock", "Poznati redatelj", "Napetost i ptice"),
        ("Neil Armstrong", "Neil Armstrong", "Poznati astronaut", "Jedan mali korak"),
        ("Coco Chanel", "Coco Chanel", "Poznata dizajnerica", "Mala crna haljina"),
    ]),
}
