# -*- coding: utf-8 -*-

HR2 = {
    "athletes": ("Poznati sportaši", [
        ("Cristiano Ronaldo", "Cristiano Ronaldo", "Poznati nogometaš", "Nikad umoran od sebe"),
        ("Lionel Messi", "Lionel Messi", "Poznati nogometaš", "Nizak i nezaustavljiv"),
        ("Michael Jordan", "Michael Jordan", "Poznati košarkaš", "Broj 23"),
        ("Serena Williams", "Serena Williams", "Poznata tenisačica", "Snaga na terenu"),
        ("Usain Bolt", "Usain Bolt", "Poznati sprinter", "Nitko nije bio blizu"),
        ("Muhammad Ali", "Muhammad Ali", "Poznati boksač", "Lebdi pa ubode"),
        ("LeBron James", "LeBron James", "Poznati košarkaš", "Još uvijek igra"),
        ("Roger Federer", "Roger Federer", "Poznati tenisač", "Vrlo pristojan pobjednik"),
        ("Tiger Woods", "Tiger Woods", "Poznati golfer", "Crvena majica nedjeljom"),
        ("Pele", "Pelé", "Poznati nogometaš", "Stari kralj"),
        ("Rafael Nadal", "Rafael Nadal", "Poznati tenisač", "Voli zemlju"),
        ("Novak Djokovic", "Novak Đoković", "Poznati tenisač", "Savije se ali ne puca"),
        ("Kobe Bryant", "Kobe Bryant", "Poznati košarkaš", "Zmija"),
        ("Neymar", "Neymar", "Poznati nogometaš", "Pada dramatično"),
        ("Lewis Hamilton", "Lewis Hamilton", "Poznati vozač", "Vrlo brzi krugovi"),
        ("Michael Phelps", "Michael Phelps", "Poznati plivač", "Zid medalja"),
        ("Maradona", "Maradona", "Poznati nogometaš", "Sumnjivi pogodak"),
        ("Simone Biles", "Simone Biles", "Poznata gimnastičarka", "Prkosi gravitaciji"),
        ("Kylian Mbappe", "Kylian Mbappé", "Poznati nogometaš", "Prebrz"),
        ("Conor McGregor", "Conor McGregor", "Poznati borac", "Prvo priča"),
        ("Wayne Gretzky", "Wayne Gretzky", "Poznati hokejaš", "Veliki"),
        ("Zinedine Zidane", "Zinedine Zidane", "Poznati nogometaš", "Slavni udarac glavom"),
        ("Shaquille O'Neal", "Shaquille O'Neal", "Poznati košarkaš", "Lomio je obruče"),
        ("Ayrton Senna", "Ayrton Senna", "Poznati vozač", "Kiša mu je bila saveznik"),
        ("Carl Lewis", "Carl Lewis", "Poznati atletičar", "Trčao je i skakao"),
        ("Nadia Comaneci", "Nadia Comăneci", "Poznata gimnastičarka", "Savršena ocjena"),
        ("Eliud Kipchoge", "Eliud Kipchoge", "Poznati trkač", "Ispod dva sata"),
        ("Katie Ledecky", "Katie Ledecky", "Poznata plivačica", "Duge i usamljene staze"),
        ("Magic Johnson", "Magic Johnson", "Poznati košarkaš", "Dodaje ono što ne vidiš"),
        ("Valentino Rossi", "Valentino Rossi", "Poznati motociklist", "Žuta i broj 46"),
    ]),

    "places": ("Poznata mjesta", [
        ("Eiffel Tower", "Eiffelov toranj", "Poznata znamenitost", "Željezo i romantika"),
        ("Great Wall of China", "Kineski zid", "Poznata znamenitost", "Vrlo duga obrana"),
        ("Pyramids of Giza", "Piramide u Gizi", "Drevna znamenitost", "Vrlo stari trokuti"),
        ("Statue of Liberty", "Kip slobode", "Poznata znamenitost", "Dar koji je ostao"),
        ("Colosseum", "Koloseum", "Drevna znamenitost", "Stara zabava"),
        ("Big Ben", "Big Ben", "Poznata znamenitost", "Glasno kaže koliko je sati"),
        ("Taj Mahal", "Taj Mahal", "Poznata znamenitost", "Sagrađen iz tuge"),
        ("Grand Canyon", "Grand Canyon", "Prirodno čudo", "Voda je bila strpljiva"),
        ("Niagara Falls", "Nijagarini slapovi", "Prirodno čudo", "Bučna voda"),
        ("Mount Everest", "Mount Everest", "Poznati vrh", "Najviši red čekanja"),
        ("Sahara Desert", "Sahara", "Prirodno područje", "Vrlo suho i vrlo veliko"),
        ("Amazon Rainforest", "Amazonska prašuma", "Prirodno područje", "Zeleno i bučno"),
        ("Stonehenge", "Stonehenge", "Drevna znamenitost", "Nitko se ne slaže zašto"),
        ("Machu Picchu", "Machu Picchu", "Drevna znamenitost", "Visoko i skriveno"),
        ("Sydney Opera House", "Sydneyska opera", "Poznata građevina", "Školjke uz vodu"),
        ("Leaning Tower of Pisa", "Kosi toranj u Pisi", "Poznata znamenitost", "Građevinska pogreška"),
        ("Times Square", "Times Square", "Poznato gradsko mjesto", "Nikad mračno"),
        ("Louvre", "Louvre", "Poznati muzej", "Staklo i jedna mala slika"),
        ("Mount Fuji", "Fuji", "Poznati vrh u Aziji", "Naslikan tisuću puta"),
        ("Golden Gate Bridge", "Golden Gate", "Poznati prijelaz", "Narančast i maglovit"),
        ("Santorini", "Santorini", "Otok za odmor", "Bijelo i plavo"),
        ("Petra", "Petra", "Drevna znamenitost", "Uklesano u stijenu"),
        ("Angkor Wat", "Angkor Wat", "Drevni hram", "Progutala ga džungla"),
        ("Chichen Itza", "Chichén Itzá", "Drevna znamenitost", "Stube i sjene"),
        ("Victoria Falls", "Viktorijini slapovi", "Prirodno čudo", "Dim koji grmi"),
        ("Dead Sea", "Mrtvo more", "Prirodno područje", "Ne možeš potonuti"),
        ("Mount Rushmore", "Mount Rushmore", "Poznata znamenitost", "Lica u kamenu"),
        ("Buckingham Palace", "Buckinghamska palača", "Poznata građevina", "Stražari koji se ne miču"),
        ("Northern Lights", "Sjeverna svjetlost", "Prirodno čudo", "Nebo nastupa"),
        ("Serengeti", "Serengeti", "Prirodno područje", "Sve seli"),
    ]),

    "animals": ("Životinje", [
        ("Dog", "Pas", "Kućni ljubimac", "Vrlo vjeran"),
        ("Cat", "Mačka", "Kućni ljubimac", "Glumi da joj nije stalo"),
        ("Elephant", "Slon", "Velika životinja", "Nikad ne zaboravlja"),
        ("Lion", "Lav", "Divlja životinja", "Prospava veći dio dana"),
        ("Penguin", "Pingvin", "Životinja hladnih krajeva", "Odjeven svečano"),
        ("Dolphin", "Dupin", "Morska životinja", "Previše pametan"),
        ("Horse", "Konj", "Domaća životinja", "Možeš ga jahati"),
        ("Monkey", "Majmun", "Životinja iz džungle", "Oponaša te"),
        ("Giraffe", "Žirafa", "Visoka životinja", "Odličan pogled"),
        ("Shark", "Morski pas", "Opasna riba", "Loš glas"),
        ("Snake", "Zmija", "Gmaz", "Noge nisu potrebne"),
        ("Rabbit", "Zec", "Mala životinja", "Brz i nervozan"),
        ("Kangaroo", "Klokan", "Australska životinja", "Ugrađeni džep"),
        ("Owl", "Sova", "Ptica", "Radi noćnu smjenu"),
        ("Octopus", "Hobotnica", "Morska životinja", "Osam rješenja"),
        ("Panda", "Panda", "Rijetka životinja", "Samo jedna hrana"),
        ("Crocodile", "Krokodil", "Gmaz", "Strpljiv i nepomičan"),
        ("Bee", "Pčela", "Kukac", "Slatka ali naoružana"),
        ("Wolf", "Vuk", "Divlja životinja", "Bolji u čoporu"),
        ("Camel", "Deva", "Pustinjska životinja", "Planira unaprijed"),
        ("Hedgehog", "Jež", "Mala životinja", "Smota se"),
        ("Flamingo", "Flamingo", "Ptica", "Stoji na jednoj nozi"),
        ("Chameleon", "Kameleon", "Gmaz", "Predomišlja se"),
        ("Sloth", "Ljenivac", "Životinja iz džungle", "Nikamo mu se ne žuri"),
        ("Platypus", "Čudnovati kljunaš", "Neobična životinja", "Djeluje kao greška"),
        ("Meerkat", "Surikata", "Pustinjska životinja", "Uvijek na straži"),
        ("Jellyfish", "Meduza", "Morska životinja", "Bez mozga, a pobjeđuje"),
        ("Peacock", "Paun", "Ptica", "Voli se pokazati"),
        ("Narwhal", "Narval", "Morska životinja", "Jedan dugi zub"),
        ("Axolotl", "Aksolotl", "Neobična životinja", "Nikad ne odraste"),
    ]),

    "vehicles": ("Vozila", [
        ("Car", "Automobil", "Cestovno vozilo", "Četiri kotača, jedan vlasnik"),
        ("Bicycle", "Bicikl", "Cestovno vozilo", "Pokreću ga noge"),
        ("Airplane", "Zrakoplov", "Zračno vozilo", "Vrlo brzi red čekanja"),
        ("Bus", "Autobus", "Javni prijevoz", "Svi ga dijele"),
        ("Train", "Vlak", "Javni prijevoz", "Prati liniju"),
        ("Motorcycle", "Motocikl", "Cestovno vozilo", "Dva kotača i buka"),
        ("Boat", "Brod", "Plovilo", "Ne treba mu cesta"),
        ("Helicopter", "Helikopter", "Zračno vozilo", "Diže se ravno gore"),
        ("Truck", "Kamion", "Veliko cestovno vozilo", "Nosi sve ostalo"),
        ("Scooter", "Romobil", "Malo vozilo", "Stani pa kreni"),
        ("Ambulance", "Hitna pomoć", "Vozi u bolnicu", "Prvo ga čuješ"),
        ("Fire Truck", "Vatrogasni kamion", "Interventno vozilo", "Crveno i glasno"),
        ("Submarine", "Podmornica", "Plovilo", "Ide prema dolje"),
        ("Tractor", "Traktor", "Poljoprivredno vozilo", "Namjerno spor"),
        ("Taxi", "Taksi", "Javni prijevoz", "Naplaćuje po kilometru"),
        ("Skateboard", "Skateboard", "Malo vozilo", "Bez kočnica"),
        ("Rocket", "Raketa", "Svemirsko vozilo", "Za većinu u jednom smjeru"),
        ("Hot Air Balloon", "Balon na vrući zrak", "Zračno vozilo", "Ne upravljaš njime"),
        ("Tram", "Tramvaj", "Javni prijevoz", "Gradske tračnice"),
        ("Ferry", "Trajekt", "Plovilo", "Nosi i automobile"),
        ("Limousine", "Limuzina", "Luksuzno vozilo", "Nepotrebno duga"),
        ("Snowmobile", "Motorne sanjke", "Zimsko vozilo", "Za mjesta gdje ceste prestaju"),
        ("Gondola", "Gondola", "Plovilo", "Netko drugi gura"),
        ("Segway", "Segway", "Malo vozilo", "Ravnoteža je poanta"),
        ("Jet Ski", "Jet ski", "Plovilo", "Ljetna buka"),
        ("Cable Car", "Žičara", "Planinsko vozilo", "Visi u zraku"),
        ("Forklift", "Viličar", "Radno vozilo", "Diže više nego što se čini"),
        ("Hovercraft", "Lebdjelica", "Neobično vozilo", "Ni cesta ni more"),
        ("Sled", "Sanjke", "Zimsko vozilo", "Idu samo nizbrdo"),
        ("Zeppelin", "Cepelin", "Zračno vozilo", "Spor i golem"),
    ]),

    "games": ("Videoigre", [
        ("Minecraft", "Minecraft", "Videoigra", "Sve je kocka"),
        ("Fortnite", "Fortnite", "Videoigra", "Zadnji koji stoji"),
        ("Tetris", "Tetris", "Klasična igra", "Oblici koji padaju"),
        ("Pac-Man", "Pac-Man", "Klasična igra", "Jedi pa bježi"),
        ("Super Mario", "Super Mario", "Videoigra", "Vodoinstalater koji skače"),
        ("FIFA", "FIFA", "Sportska videoigra", "Digitalni nogomet"),
        ("Angry Birds", "Angry Birds", "Mobilna igra", "Naciljaj pa ispali"),
        ("Pokemon", "Pokémon", "Videoigra", "Skupi ih sve"),
        ("Candy Crush", "Candy Crush", "Mobilna igra", "Spoji tri"),
        ("Roblox", "Roblox", "Videoigra", "Igra o igrama"),
        ("Call of Duty", "Call of Duty", "Pucačina", "Uvijek još jedan rat"),
        ("Grand Theft Auto", "Grand Theft Auto", "Videoigra", "Kriminal i vožnja"),
        ("The Sims", "The Sims", "Simulacija života", "Kućanski poslovi, ali zabavni"),
        ("Zelda", "Zelda", "Pustolovna igra", "Spasi i istraži"),
        ("Among Us", "Among Us", "Društvena igra", "Netko laže"),
        ("Mario Kart", "Mario Kart", "Trkaća igra", "Ovdje prijateljstva završavaju"),
        ("Sonic", "Sonic", "Klasična igra", "Plav i brz"),
        ("Counter-Strike", "Counter-Strike", "Pucačina", "Postavi ili deaktiviraj"),
        ("League of Legends", "League of Legends", "Videoigra", "Pet linija svađe"),
        ("Street Fighter", "Street Fighter", "Arkadna igra jedan na jedan", "Kombinacije tipki"),
        ("Space Invaders", "Space Invaders", "Klasična igra", "Polako se spuštaju"),
        ("Assassin's Creed", "Assassin's Creed", "Videoigra", "Povijest s kapuljačom"),
        ("Animal Crossing", "Animal Crossing", "Videoigra", "Mirno i beskonačno"),
        ("Dark Souls", "Dark Souls", "Videoigra", "Opet ćeš umrijeti"),
        ("Portal", "Portal", "Logička igra", "Dvije rupe, jedna ideja"),
        ("Overwatch", "Overwatch", "Pucačina", "Odaberi junaka"),
        ("Red Dead Redemption", "Red Dead Redemption", "Videoigra", "Konji i kajanje"),
        ("Elden Ring", "Elden Ring", "Videoigra", "Velika, pusta i okrutna"),
        ("Guitar Hero", "Guitar Hero", "Glazbena igra", "Plastični instrument"),
        ("Doom", "Doom", "Klasična pucačina", "Hodnici i demoni"),
    ]),

    "tech": ("Tehnologija", [
        ("Smartphone", "Pametni telefon", "Suvremeni uređaj", "Svi ga provjeravaju"),
        ("Laptop", "Prijenosno računalo", "Uređaj za rad", "Sklapa se"),
        ("Wi-Fi", "Wi-Fi", "Ima ga svaki dom", "Nevidljivo a nužno"),
        ("Headphones", "Slušalice", "Audio uređaj", "Privatni zvuk"),
        ("Camera", "Fotoaparat", "Uređaj", "Čuva trenutak"),
        ("Television", "Televizor", "Kućni uređaj", "Stari glavni ekran"),
        ("Keyboard", "Tipkovnica", "Dio računala", "Puno malih gumba"),
        ("Bluetooth", "Bluetooth", "Vrsta veze", "Uparivanje na kratko"),
        ("USB Stick", "USB stick", "Uređaj za pohranu", "Uvijek na krivu stranu"),
        ("Robot", "Robot", "Stroj", "Radi to umjesto tebe"),
        ("Smartwatch", "Pametni sat", "Nosivi uređaj", "Govori ti da ustaneš"),
        ("Drone", "Dron", "Leteći uređaj", "Pogled odozgo"),
        ("Printer", "Pisač", "Uredski uređaj", "Nikad ne radi iz prve"),
        ("GPS", "GPS", "Alat za navigaciju", "Zna gdje si"),
        ("Password", "Lozinka", "Sigurnosna stvar", "Zaboravlja se tjedno"),
        ("Cloud Storage", "Pohrana u oblaku", "Tehnološka usluga", "To je samo tuđe računalo"),
        ("Artificial Intelligence", "Umjetna inteligencija", "Suvremena tehnologija", "Odgovara samouvjereno"),
        ("Video Call", "Videopoziv", "Način komunikacije", "Isključen ti je mikrofon"),
        ("Touchscreen", "Zaslon na dodir", "Značajka uređaja", "S otiscima prstiju"),
        ("Electric Car", "Električni automobil", "Suvremeno vozilo", "Tih i uključen u struju"),
        ("Virtual Reality", "Virtualna stvarnost", "Suvremena tehnologija", "Staviš je da odeš"),
        ("QR Code", "QR kod", "Suvremeni simbol", "Uperi kameru"),
        ("Search Engine", "Tražilica", "Internetski alat", "Svačije prvo pitanje"),
        ("Emoji", "Emoji", "Digitalna stvar", "Osjećaji, sažeti"),
        ("3D Printer", "3D pisač", "Suvremeni stroj", "Gradi u slojevima"),
        ("Satellite", "Satelit", "Svemirska tehnologija", "Kruži i sluša"),
        ("Fingerprint Scanner", "Čitač otiska prsta", "Sigurnosna značajka", "Samo ti odgovaraš"),
        ("Solar Panel", "Solarni panel", "Energetska tehnologija", "Treba mu lijep dan"),
        ("Server", "Poslužitelj", "Računalo", "Negdje u hladnoj sobi"),
        ("Firewall", "Vatrozid", "Sigurnosna tehnologija", "Odlučuje tko ulazi"),
    ]),
}
