# -*- coding: utf-8 -*-

HR3 = {
    "music": ("Glazba", [
        ("Guitar", "Gitara", "Glazbalo", "Šest žica"),
        ("Piano", "Klavir", "Glazbalo", "Crno i bijelo"),
        ("Drums", "Bubnjevi", "Glazbalo", "Najglasniji u prostoriji"),
        ("Violin", "Violina", "Glazbalo", "Svira se gudalom"),
        ("Microphone", "Mikrofon", "Glazbena oprema", "Čini te glasnijim"),
        ("Concert", "Koncert", "Glazbeni događaj", "Svi stoje"),
        ("Rock", "Rock", "Glazbeni žanr", "Glasne gitare"),
        ("Rap", "Rap", "Glazbeni žanr", "Riječi su prve"),
        ("Choir", "Zbor", "Skupina pjevača", "Puno glasova, jedan zvuk"),
        ("Headliner", "Glavna zvijezda", "Pojam s festivala", "Namjerno svira zadnji"),
        ("Jazz", "Jazz", "Glazbeni žanr", "Pravila su neobavezna"),
        ("Opera", "Opera", "Glazbeni stil", "Dramatično i dugo"),
        ("Karaoke", "Karaoke", "Glazbena aktivnost", "Potrebna hrabrost"),
        ("Flute", "Flauta", "Glazbalo", "Postrance i prozračno"),
        ("Saxophone", "Saksofon", "Glazbalo", "Mekano i limeno"),
        ("Trumpet", "Truba", "Glazbalo", "Svijetlo i limeno"),
        ("DJ", "DJ", "Glazbena osoba", "Nikad ne odsvira ton"),
        ("Vinyl Record", "Gramofonska ploča", "Glazbeni medij", "Staro pa opet u modi"),
        ("Festival", "Festival", "Glazbeni događaj", "Blato i narukvice"),
        ("Harmonica", "Usna harmonika", "Glazbalo", "Stane u džep"),
        ("Reggae", "Reggae", "Glazbeni žanr", "Mimo takta"),
        ("Classical", "Klasika", "Glazbeni žanr", "Napisano davno"),
        ("Ukulele", "Ukulele", "Glazbalo", "Malo i veselo"),
        ("Accordion", "Harmonika", "Glazbalo", "Stišće se da bi svirala"),
        ("Bagpipes", "Gajde", "Glazbalo", "Čuju se izdaleka"),
        ("Conductor", "Dirigent", "Glazbena osoba", "Maše i svi ga slušaju"),
        ("Metronome", "Metronom", "Glazbena oprema", "Nikad ne ubrza"),
        ("Encore", "Bis", "Trenutak s koncerta", "Planirano iznenađenje"),
        ("Cello", "Violončelo", "Glazbalo", "Duboko i sjedeći"),
        ("Beatbox", "Beatbox", "Glazbena vještina", "Instrumenti nisu uključeni"),
    ]),

    "books": ("Knjige", [
        ("Harry Potter", "Harry Potter", "Poznati serijal knjiga", "Škola s tajnom"),
        ("The Hobbit", "Hobit", "Fantastična knjiga", "Vrlo dug put"),
        ("Romeo and Juliet", "Romeo i Julija", "Klasična drama", "Loša komunikacija"),
        ("The Little Prince", "Mali princ", "Poznata knjiga", "Lisica, ruža i pustinja"),
        ("Dracula", "Drakula", "Klasični roman", "Izbjegavaj noću"),
        ("Sherlock Holmes", "Sherlock Holmes", "Poznati detektivski serijal", "Sitnice su bitne"),
        ("Alice in Wonderland", "Alisa u zemlji čudesa", "Klasična knjiga", "Ništa nema smisla"),
        ("Robinson Crusoe", "Robinson Crusoe", "Klasični roman", "Predugo sam"),
        ("The Lord of the Rings", "Gospodar prstenova", "Fantastični serijal", "Vrati nakit"),
        ("Frankenstein", "Frankenstein", "Klasični roman", "Tvorac je problem"),
        ("The Hunger Games", "Igre gladi", "Popularni serijal knjiga", "Preživljavanje na televiziji"),
        ("1984", "1984", "Klasični roman", "Netko gleda"),
        ("Pride and Prejudice", "Ponos i predrasude", "Klasični roman", "Manire i novac"),
        ("Moby Dick", "Moby Dick", "Klasični roman", "Opsjednutost na moru"),
        ("Treasure Island", "Otok s blagom", "Klasična pustolovina", "Označeno je s X"),
        ("The Diary of Anne Frank", "Dnevnik Anne Frank", "Poznata ratna knjiga", "Pisano u skrivanju"),
        ("Don Quixote", "Don Quijote", "Klasični roman", "Bori se protiv krivog neprijatelja"),
        ("The Great Gatsby", "Veliki Gatsby", "Klasični roman", "Zabave i čežnja"),
        ("Animal Farm", "Životinjska farma", "Klasični roman", "Vlast mijenja ruke"),
        ("War and Peace", "Rat i mir", "Klasični roman", "Poznato teška"),
        ("The Odyssey", "Odiseja", "Drevni ep", "Dug put kući"),
        ("Crime and Punishment", "Zločin i kazna", "Klasični roman", "Krivnja radi svoje"),
        ("Les Miserables", "Jadnici", "Klasični roman", "Kruh i revolucija"),
        ("The Catcher in the Rye", "Lovac u žitu", "Klasični roman", "Svi su lažni"),
        ("Dune", "Dina", "Znanstvenofantastični roman", "Pijesak i politika"),
        ("The Da Vinci Code", "Da Vincijev kod", "Popularni triler", "Umjetnost krije odgovore"),
        ("Anna Karenina", "Ana Karenjina", "Klasični roman", "Vlakovi i slomljeno srce"),
        ("Charlotte's Web", "Charlottina mreža", "Dječja knjiga", "Prijateljstvo u staji"),
        ("The Jungle Book", "Knjiga o džungli", "Dječji klasik", "Odgojili ga drugi"),
        ("Encyclopedia", "Enciklopedija", "Vrsta knjige", "Nitko je ne pročita cijelu"),
    ]),

    "brands": ("Tvrtke i brendovi", [
        ("Coca-Cola", "Coca-Cola", "Poznati brend", "Crveno i gazirano"),
        ("Nike", "Nike", "Sportski brend", "Samo kvačica"),
        ("Apple", "Apple", "Tehnološki brend", "Voće i telefoni"),
        ("McDonald's", "McDonald's", "Brend brze hrane", "Zlatni lukovi"),
        ("Google", "Google", "Tehnološki brend", "Prvo mjesto gdje pitaš"),
        ("Adidas", "Adidas", "Sportski brend", "Tri crte"),
        ("Netflix", "Netflix", "Zabavni brend", "Još uvijek gledaš?"),
        ("Lego", "Lego", "Brend igračaka", "Bolno kad staneš na to"),
        ("Ferrari", "Ferrari", "Automobilski brend", "Glasan i crven"),
        ("Amazon", "Amazon", "Internetski brend", "Stiže sutra"),
        ("Samsung", "Samsung", "Tehnološki brend", "Onaj drugi telefon"),
        ("Starbucks", "Starbucks", "Brend kave", "Tvoje ime, krivo napisano"),
        ("IKEA", "IKEA", "Brend namještaja", "Potrebno je sastaviti"),
        ("Toyota", "Toyota", "Automobilski brend", "Pouzdano dosadna"),
        ("Disney", "Disney", "Zabavni brend", "Posjeduje tvoje djetinjstvo"),
        ("YouTube", "YouTube", "Internetski brend", "Preskoči oglas za pet"),
        ("Spotify", "Spotify", "Glazbeni brend", "Tvoja godina, sažeta"),
        ("Tesla", "Tesla", "Automobilski brend", "Uključen u struju i svojeglav"),
        ("Gucci", "Gucci", "Modni brend", "Namjerno skup"),
        ("Rolex", "Rolex", "Brend satova", "Govori više od vremena"),
        ("PlayStation", "PlayStation", "Igraći brend", "Četiri simbola"),
        ("Microsoft", "Microsoft", "Tehnološki brend", "Iza većine ureda"),
        ("Pepsi", "Pepsi", "Brend pića", "Uvijek drugi"),
        ("Instagram", "Instagram", "Društveni brend", "Kvadrati najboljeg dana"),
        ("Uber", "Uber", "Uslužni brend", "Netko drugi vozi"),
        ("Red Bull", "Red Bull", "Brend pića", "Navodno daje krila"),
        ("Lamborghini", "Lamborghini", "Automobilski brend", "Vrata se otvaraju naopako"),
        ("Chanel", "Chanel", "Modni brend", "Dva okrenuta slova"),
        ("Michelin", "Michelin", "Brend guma", "Ocjenjuje i restorane"),
        ("Nintendo", "Nintendo", "Igraći brend", "Zabava prije snage"),
        ("Louis Vuitton", "Louis Vuitton", "Modni brend", "Inicijali posvuda"),
        ("Heineken", "Heineken", "Brend pića", "Zelena boca"),
        ("Volkswagen", "Volkswagen", "Automobilski brend", "Narodni automobil"),
    ]),

    "countries": ("Države", [
        ("Italy", "Italija", "Europska država", "Oblikom podsjeća na čizmu"),
        ("France", "Francuska", "Europska država", "Kruh i toranj"),
        ("Japan", "Japan", "Azijska država", "Otoci i red"),
        ("Brazil", "Brazil", "Južnoamerička država", "Nogomet i prašuma"),
        ("Egypt", "Egipat", "Afrička država", "Vrlo stare građevine"),
        ("Australia", "Australija", "Država i kontinent", "Sve ugriza"),
        ("Canada", "Kanada", "Sjevernoamerička država", "Pristojno i hladno"),
        ("Mexico", "Meksiko", "Sjevernoamerička država", "Začini i boje"),
        ("Spain", "Španjolska", "Europska država", "Kasne večere"),
        ("India", "Indija", "Azijska država", "Vrlo puno ljudi"),
        ("Germany", "Njemačka", "Europska država", "Automobili i točnost"),
        ("China", "Kina", "Azijska država", "Napravila je većinu toga"),
        ("Greece", "Grčka", "Europska država", "Ruševine i otoci"),
        ("Norway", "Norveška", "Europska država", "Duga voda, kratki dani"),
        ("Croatia", "Hrvatska", "Europska država", "Duga i uska obala"),
        ("Switzerland", "Švicarska", "Europska država", "Neutralna i skupa"),
        ("Argentina", "Argentina", "Južnoamerička država", "Govedina i tango"),
        ("Netherlands", "Nizozemska", "Europska država", "Ravno i na biciklu"),
        ("South Korea", "Južna Koreja", "Azijska država", "Pop i tehnologija"),
        ("Turkey", "Turska", "Država na dva kontinenta", "Između dva svijeta"),
        ("Iceland", "Island", "Europska država", "Vatra ispod leda"),
        ("Portugal", "Portugal", "Europska država", "Okrenut oceanu"),
        ("Morocco", "Maroko", "Afrička država", "Tržnice i čaj od metvice"),
        ("Thailand", "Tajland", "Azijska država", "Plaže i ulična hrana"),
        ("New Zealand", "Novi Zeland", "Otočna država", "Više ovaca nego ljudi"),
        ("Kenya", "Kenija", "Afrička država", "Trkači i divljina"),
        ("Peru", "Peru", "Južnoamerička država", "Visoko i drevno"),
        ("Finland", "Finska", "Europska država", "Tiho i vruće u sauni"),
        ("Vietnam", "Vijetnam", "Azijska država", "Skuteri posvuda"),
        ("Ireland", "Irska", "Europska država", "Zeleno i pjesničko"),
        ("Chile", "Čile", "Južnoamerička država", "Dug i uzak"),
    ]),

    "cities": ("Gradovi", [
        ("Paris", "Pariz", "Europski grad", "Romantika i redovi"),
        ("London", "London", "Europski grad", "Kiša i crveni autobusi"),
        ("New York", "New York", "Američki grad", "Nikad ne spava"),
        ("Tokyo", "Tokio", "Azijski grad", "Golem i pristojan"),
        ("Rome", "Rim", "Europski grad", "Povijest pod nogama"),
        ("Barcelona", "Barcelona", "Europski grad", "Nedovršena crkva"),
        ("Dubai", "Dubai", "Bliskoistočni grad", "Sve noviji i viši"),
        ("Venice", "Venecija", "Europski grad", "Ulice od vode"),
        ("Berlin", "Berlin", "Europski grad", "Zid koji je pao"),
        ("Los Angeles", "Los Angeles", "Američki grad", "Gužva i kamere"),
        ("Sydney", "Sydney", "Australski grad", "Luka i školjke"),
        ("Amsterdam", "Amsterdam", "Europski grad", "Bicikli i kanali"),
        ("Istanbul", "Istanbul", "Grad na dva kontinenta", "Dvije strane, jedan grad"),
        ("Rio de Janeiro", "Rio de Janeiro", "Južnoamerički grad", "Plaža i karneval"),
        ("Moscow", "Moskva", "Europski grad", "Crveni trg"),
        ("Prague", "Prag", "Europski grad", "Mostovi i tornjevi"),
        ("Las Vegas", "Las Vegas", "Američki grad", "Blještavo i skupo"),
        ("Cairo", "Kairo", "Afrički grad", "Uz stare trokute"),
        ("Athens", "Atena", "Europski grad", "Ruševine na brdu"),
        ("Lisbon", "Lisabon", "Europski grad", "Pločice i tramvaji"),
        ("Singapore", "Singapur", "Azijski grad", "Čist po zakonu"),
        ("Hong Kong", "Hong Kong", "Azijski grad", "Život u visinu"),
        ("Vienna", "Beč", "Europski grad", "Kava i skladatelji"),
        ("Buenos Aires", "Buenos Aires", "Južnoamerički grad", "Odrezak i ples"),
        ("Cape Town", "Cape Town", "Afrički grad", "Ravna planina"),
        ("Marrakesh", "Marakeš", "Afrički grad", "Labirint štandova"),
        ("Copenhagen", "Kopenhagen", "Europski grad", "Dizajn i bicikli"),
        ("Seoul", "Seul", "Azijski grad", "Brzo i blještavo"),
        ("Dubrovnik", "Dubrovnik", "Europski grad", "Zidine uz more"),
        ("Reykjavik", "Reykjavík", "Europski grad", "Malen i sjeverni"),
    ]),
}
