# -*- coding: utf-8 -*-

HR4 = {
    "vacation": ("Odmor i putovanja", [
        ("Beach", "Plaža", "Mjesto za odmor", "Pijesak dođe posvuda"),
        ("Hotel", "Hotel", "Mjesto za odmor", "Netko drugi sprema krevet"),
        ("Cruise", "Krstarenje", "Vrsta odmora", "Hotel se kreće"),
        ("Camping", "Kampiranje", "Vrsta odmora", "Priroda, neudobno"),
        ("Ski Resort", "Skijalište", "Zimsko odmaralište", "Hladno i skupo"),
        ("Maldives", "Maldivi", "Odredište za odmor", "Voda na sve strane"),
        ("Hawaii", "Havaji", "Odredište za odmor", "Cvijeće i vulkani"),
        ("Theme Park", "Zabavni park", "Mjesto za odmor", "Čekaj pa vrišti"),
        ("Road Trip", "Putovanje autom", "Vrsta odmora", "Poanta je u putu"),
        ("Bali", "Bali", "Odredište za odmor", "Hramovi i surfanje"),
        ("Safari", "Safari", "Vrsta odmora", "Gledaj, ne diraj"),
        ("Ibiza", "Ibiza", "Odredište za odmor", "Spavanje nije obavezno"),
        ("Swimming Pool", "Bazen", "Sadržaj na odmoru", "Plav i pun"),
        ("Backpacking", "Putovanje s ruksakom", "Vrsta odmora", "Sve svoje nosiš na ramenima"),
        ("Cabin", "Brvnara", "Mjesto za odmor", "Drvo i tišina"),
        ("All-Inclusive", "All inclusive", "Vrsta odmora", "Plaćeno unaprijed"),
        ("Airport", "Zračna luka", "Dio putovanja", "Profesionalno čekanje"),
        ("Souvenir", "Suvenir", "Stvar s odmora", "Kod kuće ti je žao"),
        ("Cancun", "Cancún", "Odredište za odmor", "Tirkizno i prometno"),
        ("Amalfi Coast", "Amalfijska obala", "Odredište za odmor", "Litice i limuni"),
        ("Northern Ireland", "Sjeverna Irska", "Putno odredište", "Zeleno i vjetrovito"),
        ("Yosemite", "Yosemite", "Nacionalni park", "Granit i slapovi"),
        ("Patagonia", "Patagonija", "Putno odredište", "Vjetar na kraju svijeta"),
        ("Hostel", "Hostel", "Mjesto za odmor", "Jeftino i društveno"),
        ("Sunburn", "Opeklina od sunca", "Nezgoda na odmoru", "Kajanje koje se osjeti"),
        ("Passport", "Putovnica", "Dokument koji trebaš na granici", "Fotografija je grozna"),
        ("Snorkelling", "Ronjenje s maskom", "Aktivnost na odmoru", "Gledaj dolje, diši gore"),
        ("Glamping", "Glamping", "Vrsta odmora", "Priroda s madracem"),
        ("Mount Kilimanjaro", "Kilimanjaro", "Putno odredište", "Penji se polako"),
        ("Lake District", "Lake District", "Putno odredište", "Voda i planinarske cipele"),
    ]),

    "jobs": ("Zanimanja", [
        ("Doctor", "Liječnik", "Zanimanje", "Pita gdje boli"),
        ("Teacher", "Učitelj", "Zanimanje", "Objašnjava ponovno"),
        ("Firefighter", "Vatrogasac", "Zanimanje", "Trči prema tome"),
        ("Chef", "Kuhar", "Zanimanje", "Vruće i s vikanjem"),
        ("Police Officer", "Policajac", "Zanimanje", "Postavlja pitanja"),
        ("Pilot", "Pilot", "Zanimanje", "Najavljuje vrijeme"),
        ("Nurse", "Medicinska sestra", "Zanimanje", "Ona koja stvarno pomogne"),
        ("Farmer", "Poljoprivrednik", "Zanimanje", "Budan prije svih"),
        ("Dentist", "Zubar", "Zanimanje", "Nitko se ne veseli"),
        ("Lawyer", "Odvjetnik", "Zanimanje", "Čita sitna slova"),
        ("Engineer", "Inženjer", "Zanimanje", "Postiže da radi"),
        ("Photographer", "Fotograf", "Zanimanje", "Čeka svjetlo"),
        ("Journalist", "Novinar", "Zanimanje", "Postavlja neugodno pitanje"),
        ("Architect", "Arhitekt", "Zanimanje", "Crta prije gradnje"),
        ("Barber", "Brijač", "Zanimanje", "Kratak razgovor, kraća kosa"),
        ("Mechanic", "Automehaničar", "Zanimanje", "Dijagnosticira po zvuku"),
        ("Scientist", "Znanstvenik", "Zanimanje", "Uglavnom griješi namjerno"),
        ("Accountant", "Računovođa", "Zanimanje", "Brojevi se moraju slagati"),
        ("Electrician", "Električar", "Zanimanje", "Ne diraj to"),
        ("Waiter", "Konobar", "Zanimanje", "Pamti tvoju narudžbu"),
        ("Librarian", "Knjižničar", "Zanimanje", "Održava tišinu"),
        ("Plumber", "Vodoinstalater", "Zanimanje", "Dolazi kad je prekasno"),
        ("Veterinarian", "Veterinar", "Zanimanje", "Pacijent ne može objasniti"),
        ("Translator", "Prevoditelj", "Zanimanje", "Stoji između dvoje ljudi"),
        ("Astronaut", "Astronaut", "Zanimanje", "Vrlo malo radnih mjesta"),
        ("Lifeguard", "Spasilac", "Zanimanje", "Gleda i čeka"),
        ("Referee", "Sudac", "Zanimanje", "Svi se ne slažu"),
        ("Archaeologist", "Arheolog", "Zanimanje", "Kopa za starim stvarima"),
        ("Air Traffic Controller", "Kontrolor leta", "Zanimanje", "Nema mjesta za pogrešku"),
        ("Sommelier", "Someljer", "Zanimanje", "Zna godinu"),
        ("Actuary", "Aktuar", "Zanimanje", "Predviđa ono malo vjerojatno"),
        ("Zookeeper", "Čuvar u zoološkom", "Zanimanje", "Hrani neobične"),
    ]),

    "hobbies": ("Hobiji", [
        ("Painting", "Slikanje", "Kreativni hobi", "Boja na podlozi"),
        ("Reading", "Čitanje", "Miran hobi", "Stranicu po stranicu"),
        ("Gardening", "Vrtlarenje", "Hobi na otvorenom", "Potrebno strpljenje"),
        ("Cooking", "Kuhanje", "Kućni hobi", "Kušaš prije kraja"),
        ("Photography", "Fotografija", "Kreativni hobi", "Zamrzni trenutak"),
        ("Fishing", "Pecanje", "Hobi na otvorenom", "Uglavnom čekanje"),
        ("Dancing", "Ples", "Aktivan hobi", "Kreći se uz zvuk"),
        ("Singing", "Pjevanje", "Glazbeni hobi", "Najbolje pod tušem"),
        ("Hiking", "Planinarenje", "Hobi na otvorenom", "Hodanje s pogledom"),
        ("Drawing", "Crtanje", "Kreativni hobi", "Prvo linije"),
        ("Knitting", "Pletenje", "Rukotvorni hobi", "Petlja za petljom"),
        ("Chess", "Šah", "Hobi u zatvorenom", "Misli prije nego dotakneš"),
        ("Puzzles", "Slagalice", "Hobi u zatvorenom", "Prvo rubovi"),
        ("Baking", "Pečenje kolača", "Kućni hobi", "Mjeri točno"),
        ("Collecting", "Skupljanje", "Hobi", "Nikad sasvim potpuno"),
        ("Yoga", "Joga", "Hobi za dobro stanje", "Diši i zadrži"),
        ("Camping", "Kampiranje", "Hobi na otvorenom", "Namjerno spavaš vani"),
        ("Woodworking", "Obrada drva", "Rukotvorni hobi", "Mjeri dvaput"),
        ("Birdwatching", "Promatranje ptica", "Hobi na otvorenom", "Tiho i s nadom"),
        ("Journaling", "Vođenje dnevnika", "Miran hobi", "Samo za tvoje oči"),
        ("Pottery", "Lončarstvo", "Rukotvorni hobi", "Vrti se dok oblikuješ"),
        ("Board Games", "Društvene igre", "Hobi u zatvorenom", "Prijateljstva na kušnji"),
        ("Karaoke", "Karaoke", "Društveni hobi", "Hrabrost preko talenta"),
        ("Origami", "Origami", "Rukotvorni hobi", "Presavijanje, bez rezanja"),
        ("Calligraphy", "Kaligrafija", "Kreativni hobi", "Sporo i lijepo pisanje"),
        ("Astronomy", "Astronomija", "Noćni hobi", "Gledaš vrlo daleko unatrag"),
        ("Scrapbooking", "Izrada albuma", "Rukotvorni hobi", "Uspomene s ljepilom"),
        ("Geocaching", "Geocaching", "Hobi na otvorenom", "Negdje je skrivena kutija"),
        ("Model Building", "Izrada maketa", "Rukotvorni hobi", "Sitno i strpljivo"),
        ("Rollerblading", "Rolanje", "Aktivan hobi", "Kotači na nogama"),
    ]),

    "tvshows": ("TV serije", [
        ("Friends", "Prijatelji", "Poznata serija", "Šestero ljudi, jedan kauč"),
        ("The Simpsons", "Simpsoni", "Animirana serija", "Žuti i beskonačni"),
        ("Game of Thrones", "Igra prijestolja", "Poznata serija", "Nitko nije siguran"),
        ("Stranger Things", "Stranger Things", "Popularna serija", "Osamdesete su pošle po zlu"),
        ("SpongeBob", "Spužva Bob", "Animirana serija", "Živi pod morem"),
        ("Breaking Bad", "Breaking Bad", "Poznata serija", "Profesor mijenja karijeru"),
        ("The Office", "Ured", "Humoristična serija", "Kamera sve snima"),
        ("Tom and Jerry", "Tom i Jerry", "Animirana serija", "Bez dijaloga"),
        ("Pokemon", "Pokémon", "Animirana serija", "Uhvati ih sve"),
        ("Sherlock", "Sherlock", "Krimi serija", "Primjećuje sve"),
        ("Money Heist", "Kuća od papira", "Popularna serija", "Crvena odijela i maske"),
        ("The Crown", "Kruna", "Dramska serija", "Stvarni ljudi, dramatizirano"),
        ("Squid Game", "Squid Game", "Popularna serija", "Dječje igre, smrtne posljedice"),
        ("Peaky Blinders", "Peaky Blinders", "Dramska serija", "Kape i prijetnje"),
        ("Big Bang Theory", "Teorija velikog praska", "Humoristična serija", "Pametni i nespretni"),
        ("Rick and Morty", "Rick i Morty", "Animirana serija", "Znanost i kaos"),
        ("The Mandalorian", "Mandalorac", "Znanstvenofantastična serija", "Kaciga ostaje"),
        ("How I Met Your Mother", "Kako sam upoznao vašu majku", "Humoristična serija", "Vrlo duga priča"),
        ("Grey's Anatomy", "Uvod u anatomiju", "Dramska serija", "Bolnica i slomljena srca"),
        ("Black Mirror", "Crno zrcalo", "Dramska serija", "Tehnologija pođe po zlu"),
        ("MasterChef", "MasterChef", "Reality serija", "Ocjenjuje se okusom"),
        ("Top Gear", "Top Gear", "Reality serija", "Automobili i svađe"),
        ("Family Guy", "Obiteljski čovjek", "Animirana serija", "Prekinuto sjećanjima"),
        ("Narcos", "Narcos", "Dramska serija", "Prah i moć"),
        ("The Witcher", "Vještac", "Fantastična serija", "Sijeda kosa, čudovišta"),
        ("Chernobyl", "Černobil", "Dramska serija", "Nešto nevidljivo"),
        ("Suits", "Odijela", "Dramska serija", "Oštra odjeća, oštriji jezik"),
        ("Dexter", "Dexter", "Krimi serija", "Radi za obje strane"),
        ("Lost", "Izgubljeni", "Poznata serija", "Nitko nije shvatio kraj"),
        ("Downton Abbey", "Downton Abbey", "Dramska serija", "Sluge i njihovi gospodari"),
    ]),

    "superheroes": ("Superjunaci", [
        ("Superman", "Superman", "Izmišljeni junak", "Samo jedna slabost"),
        ("Batman", "Batman", "Izmišljeni junak", "Bez moći, samo novac"),
        ("Spider-Man", "Spider-Man", "Izmišljeni junak", "Lijepi se za zidove"),
        ("Iron Man", "Iron Man", "Izmišljeni junak", "Odijelo je moć"),
        ("Wonder Woman", "Wonder Woman", "Izmišljena junakinja", "Istina putem užeta"),
        ("Hulk", "Hulk", "Izmišljeni junak", "Problem s bijesom"),
        ("Captain America", "Kapetan Amerika", "Izmišljeni junak", "Okrugli štit"),
        ("Thor", "Thor", "Izmišljeni junak", "Samo ga on može podići"),
        ("Black Panther", "Crna Pantera", "Izmišljeni junak", "Skriveno kraljevstvo"),
        ("Flash", "Flash", "Izmišljeni junak", "Stigne prije nego završiš"),
        ("Wolverine", "Wolverine", "Izmišljeni junak", "Zacjeljuje i reže"),
        ("Deadpool", "Deadpool", "Izmišljeni junak", "Priča s tobom"),
        ("Aquaman", "Aquaman", "Izmišljeni junak", "Vlada vodom"),
        ("Doctor Strange", "Doctor Strange", "Izmišljeni junak", "Magija i portali"),
        ("Black Widow", "Crna Udovica", "Izmišljena junakinja", "Bez moći, sve trening"),
        ("Green Lantern", "Zeleni Fenjer", "Izmišljeni junak", "Volja i prsten"),
        ("Ant-Man", "Ant-Man", "Izmišljeni junak", "Veličina je trik"),
        ("Catwoman", "Žena mačka", "Izmišljeni lik", "Nije baš junakinja"),
        ("Joker", "Joker", "Izmišljeni zlikovac", "Smije se u krivi čas"),
        ("Thanos", "Thanos", "Izmišljeni zlikovac", "Vjeruje u ravnotežu"),
        ("Loki", "Loki", "Izmišljeni lik", "Nikad dvaput isti"),
        ("Captain Marvel", "Kapetanica Marvel", "Izmišljena junakinja", "Sjaji i leti"),
        ("Hawkeye", "Hawkeye", "Izmišljeni junak", "Donio je luk u rat"),
        ("Robin", "Robin", "Izmišljeni junak", "Uvijek drugi"),
        ("Groot", "Groot", "Izmišljeni lik", "Samo tri riječi"),
        ("Magneto", "Magneto", "Izmišljeni zlikovac", "Metal ga sluša"),
        ("Silver Surfer", "Srebrni Letač", "Izmišljeni junak", "Jaše kroz svemir"),
        ("Storm", "Oluja", "Izmišljena junakinja", "Vrijeme po narudžbi"),
        ("Venom", "Venom", "Izmišljeni lik", "Nosi svog domaćina"),
        ("Professor X", "Profesor X", "Izmišljeni junak", "Doslovno čita prostoriju"),
    ]),
}
