# -*- coding: utf-8 -*-

HR5 = {
    "drinks": ("Pića", [
        ("Water", "Voda", "Napitak", "Zadana opcija"),
        ("Coffee", "Kava", "Topli napitak", "Jutarnja obaveza"),
        ("Tea", "Čaj", "Topli napitak", "Listovi i strpljenje"),
        ("Orange Juice", "Sok od naranče", "Hladni napitak", "Doručak u čaši"),
        ("Milk", "Mlijeko", "Napitak", "Ide uz pahuljice"),
        ("Lemonade", "Limunada", "Hladni napitak", "Slatko i oštro"),
        ("Hot Chocolate", "Vruća čokolada", "Topli napitak", "Zimska utjeha"),
        ("Smoothie", "Smoothie", "Hladni napitak", "Voće, izmiksano"),
        ("Milkshake", "Milkshake", "Hladni napitak", "Gust i sladak"),
        ("Iced Tea", "Ledeni čaj", "Hladni napitak", "Ljeto u čaši"),
        ("Cappuccino", "Cappuccino", "Kavni napitak", "Pjena na vrhu"),
        ("Espresso", "Espresso", "Kavni napitak", "Malen ali ozbiljan"),
        ("Cola", "Kola", "Gazirani napitak", "Tamna i mjehurićava"),
        ("Energy Drink", "Energetsko piće", "Suvremeni napitak", "Prodaje se kao hrabrost"),
        ("Coconut Water", "Kokosova voda", "Tropski napitak", "Ravno iz ljuske"),
        ("Mojito", "Mojito", "Koktel", "Metvica i led"),
        ("Sangria", "Sangria", "Španjolski napitak", "Voće pliva u njemu"),
        ("Pina Colada", "Piña Colada", "Koktel", "Odmor u čaši"),
        ("Cider", "Jabukovača", "Napitak", "Fermentirano voće"),
        ("Sparkling Water", "Gazirana voda", "Mjehurićavi napitak", "Bez okusa, samo mjehurići"),
        ("Latte", "Latte", "Kavni napitak", "Uglavnom mlijeko"),
        ("Green Tea", "Zeleni čaj", "Topli napitak", "Smirujuće i travnato"),
        ("Ginger Ale", "Ginger ale", "Gazirani napitak", "Smiruje želudac"),
        ("Root Beer", "Root beer", "Gazirani napitak", "Nekima ima okus lijeka"),
        ("Matcha", "Matcha", "Suvremeni napitak", "Jarko zeleni prah"),
        ("Kombucha", "Kombucha", "Suvremeni napitak", "Tehnički gledano, živo"),
        ("Horchata", "Horchata", "Tradicionalni napitak", "Slatko, mliječno i začinjeno"),
        ("Turkish Coffee", "Turska kava", "Tradicionalni topli napitak", "Nemoj popiti dno"),
        ("Bubble Tea", "Bubble tea", "Suvremeni napitak", "Žvakava iznenađenja"),
        ("Sports Drink", "Izotonik", "Napitak za sportaše", "Boja je okus"),
    ]),

    "clothing": ("Odjeća", [
        ("T-Shirt", "Majica", "Odjevni predmet", "Zadani gornji dio"),
        ("Jeans", "Traperice", "Odjevni predmet", "Plave i posvuda"),
        ("Jacket", "Jakna", "Odjevni predmet", "Za put kući"),
        ("Socks", "Čarape", "Odjevni predmet", "Jedna uvijek nestane"),
        ("Hat", "Šešir", "Odjevni predmet", "Nosi se na vrhu"),
        ("Scarf", "Šal", "Odjevni predmet", "Omotan oko"),
        ("Dress", "Haljina", "Odjevni predmet", "Jedan komad"),
        ("Sneakers", "Tenisice", "Obuća", "Za hodanje ili za izgled"),
        ("Gloves", "Rukavice", "Odjevni predmet", "Pet prstiju svaka"),
        ("Pyjamas", "Pidžama", "Odjevni predmet", "Viđa se samo doma"),
        ("Sweater", "Džemper", "Odjevni predmet", "Topao i pleten"),
        ("Boots", "Čizme", "Obuća", "Za loše vrijeme"),
        ("Suit", "Odijelo", "Odjevni predmet", "Za ozbiljne dane"),
        ("Swimsuit", "Kupaći kostim", "Odjevni predmet", "Namijenjen da se smoči"),
        ("Raincoat", "Kabanica", "Odjevni predmet", "Drži nebo vani"),
        ("Hoodie", "Hoodica", "Odjevni predmet", "Navuci je i nestani"),
        ("Belt", "Remen", "Modni dodatak", "Drži stvari gore"),
        ("Tie", "Kravata", "Modni dodatak", "Čvor s pravilima"),
        ("Flip Flops", "Japanke", "Obuća", "Najave tvoj dolazak"),
        ("Sunglasses", "Sunčane naočale", "Modni dodatak", "Pola maske"),
        ("Skirt", "Suknja", "Odjevni predmet", "Noge nisu razdvojene"),
        ("Uniform", "Uniforma", "Vrsta odjeće", "Svi izgledaju isto"),
        ("Apron", "Pregača", "Odjevni predmet", "Štiti ostalo"),
        ("Blazer", "Sako", "Odjevni predmet", "Uredno ali ne svečano"),
        ("High Heels", "Štikle", "Obuća", "Visina uz cijenu"),
        ("Kimono", "Kimono", "Tradicionalna odjeća", "Omotano i vezano"),
        ("Poncho", "Pončo", "Odjevni predmet", "Jedna rupa za glavu"),
        ("Tuxedo", "Smoking", "Svečana odjeća", "Obavezna leptir mašna"),
        ("Beanie", "Kapa", "Odjevni predmet", "Topla i opuštena"),
        ("Cufflinks", "Manžete", "Modni dodatak", "Sitno i nepotrebno"),
        ("Cardigan", "Kardigan", "Odjevni predmet", "Gumbi do dolje"),
    ]),

    "school": ("Škola i obrazovanje", [
        ("Homework", "Domaća zadaća", "Školska stvar", "Škola koja te prati"),
        ("Teacher", "Učitelj", "Osoba u školi", "Objašnjava ponovno"),
        ("Exam", "Ispit", "Školski događaj", "Tišina i znojenje"),
        ("Blackboard", "Ploča", "Predmet u učionici", "Prašina i kreda"),
        ("Backpack", "Ruksak", "Školski predmet", "Svake godine teži"),
        ("Pencil", "Olovka", "Školski predmet", "Greške su dopuštene"),
        ("Library", "Knjižnica", "Mjesto u školi", "Tišina po pravilu"),
        ("Recess", "Odmor", "Trenutak u školi", "Prava lekcija"),
        ("Notebook", "Bilježnica", "Školski predmet", "Prazna pa puna"),
        ("Mathematics", "Matematika", "Školski predmet", "Brojevi se prepiru"),
        ("History", "Povijest", "Školski predmet", "Već se dogodilo"),
        ("Chemistry", "Kemija", "Školski predmet", "Stvari mijenjaju oblik"),
        ("Report Card", "Svjedodžba", "Školski dokument", "Nerado se pokazuje"),
        ("Detention", "Ostanak poslije nastave", "Školska kazna", "Vrijeme koje duguješ"),
        ("Graduation", "Matura", "Školski događaj", "Kape u zrak"),
        ("Uniform", "Uniforma", "Školski predmet", "Nikome nije najdraža"),
        ("School Bus", "Vozilo za učenike", "Prijevoz do nastave", "Žuto i rano"),
        ("Field Trip", "Izlet", "Školski događaj", "Navodno se uči"),
        ("Cafeteria", "Kantina", "Mjesto u školi", "Pladnjevi i redovi"),
        ("Principal", "Ravnatelj", "Osoba u školi", "Rijetko dobre vijesti"),
        ("Calculator", "Kalkulator", "Školski predmet", "Ponekad zabranjen"),
        ("Whiteboard", "Bijela ploča", "Predmet u učionici", "Kriv flomaster je uništi"),
        ("Geography", "Geografija", "Školski predmet", "Gdje se što nalazi"),
        ("Biology", "Biologija", "Školski predmet", "Živa bića"),
        ("Diploma", "Diploma", "Školski dokument", "Papir koji je trajao godinama"),
        ("Substitute Teacher", "Zamjena", "Osoba u školi", "Ništa se ne odradi"),
        ("Parent-Teacher Meeting", "Roditeljski sastanak", "Školski događaj", "Dva svijeta se sudare"),
        ("Semester", "Semestar", "Dio školske godine", "Komad godine"),
        ("Scholarship", "Stipendija", "Stvar u obrazovanju", "Netko drugi plaća"),
        ("Thesis", "Diplomski rad", "Stvar u obrazovanju", "Vrlo dug i brani se"),
    ]),

    "nature": ("Priroda i vrijeme", [
        ("Rain", "Kiša", "Vrsta vremena", "Nebo popusti"),
        ("Snow", "Snijeg", "Vrsta vremena", "Tiho i hladno"),
        ("Rainbow", "Duga", "Vremenska pojava", "Nakon lošeg dijela"),
        ("Thunder", "Grmljavina", "Zvuk s neba", "Kasni za svojim svjetlom"),
        ("Lightning", "Munja", "Vremenska pojava", "Svijetla i kratka"),
        ("Wind", "Vjetar", "Vrsta vremena", "Osjeti se, ne vidi"),
        ("Sun", "Sunce", "Na nebu", "Sve ovisi o njemu"),
        ("Moon", "Mjesec", "Na nebu", "Posuđeno svjetlo"),
        ("Cloud", "Oblak", "Na nebu", "Oblici za dosadne"),
        ("Fog", "Magla", "Vrsta vremena", "Svijet se smanji"),
        ("Ocean", "Ocean", "Prirodno mjesto", "Uglavnom neistražen"),
        ("Mountain", "Planina", "Prirodno mjesto", "Sve više i više"),
        ("Forest", "Šuma", "Prirodno mjesto", "Puna a tiha"),
        ("River", "Rijeka", "Prirodno mjesto", "Uvijek odlazi"),
        ("Desert", "Pustinja", "Prirodno mjesto", "Sve je strpljivo"),
        ("Volcano", "Vulkan", "Prirodna tvorba", "Spava, pa ne spava"),
        ("Earthquake", "Potres", "Prirodna pojava", "Tlo se ne slaže"),
        ("Hurricane", "Uragan", "Vremenska pojava", "Mir u sredini"),
        ("Tornado", "Tornado", "Vremenska pojava", "Nevolja koja se vrti"),
        ("Waterfall", "Slap", "Prirodna tvorba", "Rijeka odustane"),
        ("Sunset", "Zalazak sunca", "Svakodnevna pojava", "Svi ga slikaju"),
        ("Glacier", "Ledenjak", "Prirodna tvorba", "Spor ali moćan"),
        ("Island", "Otok", "Prirodno mjesto", "Okružen"),
        ("Cave", "Špilja", "Prirodno mjesto", "Mračno i staro"),
        ("Frost", "Mraz", "Vrsta vremena", "Noćni ukras"),
        ("Hail", "Tuča", "Vrsta vremena", "Kiša koja boli"),
        ("Drought", "Suša", "Vremenska pojava", "Ništa ne stiže"),
        ("Avalanche", "Lavina", "Prirodna pojava", "Previše odjednom"),
        ("Monsoon", "Monsun", "Vremensko razdoblje", "Ozbiljno se posveti"),
        ("Eclipse", "Pomrčina", "Pojava na nebu", "Nešto stane na put"),
        ("Tundra", "Tundra", "Prirodno mjesto", "Smrznuto i bez drveća"),
    ]),
}
