E, M, H = "easy", "medium", "hard"

PART5 = {
    "drinks": ("Drinks", "\U0001F379", [
        ("Water", "A drink", "The default one", E),
        ("Coffee", "A hot drink", "The morning requirement", E),
        ("Tea", "A hot drink", "Leaves and patience", E),
        ("Orange Juice", "A cold drink", "Breakfast in a glass", E),
        ("Milk", "A drink", "Goes with cereal", E),
        ("Lemonade", "A cold drink", "Sweet and sharp", E),
        ("Hot Chocolate", "A hot drink", "Winter comfort", E),
        ("Smoothie", "A cold drink", "Fruit, blended", E),
        ("Milkshake", "A cold drink", "Thick and sweet", E),
        ("Iced Tea", "A cold drink", "Summer in a glass", E),
        ("Cappuccino", "A coffee drink", "Foam on top", M),
        ("Espresso", "A coffee drink", "Small but serious", M),
        ("Cola", "A fizzy drink", "Dark and bubbly", M),
        ("Energy Drink", "A modern beverage", "Sold as courage", M),
        ("Coconut Water", "A tropical drink", "Straight from the shell", M),
        ("Mojito", "A cocktail", "Mint and ice", M),
        ("Sangria", "A Spanish drink", "Fruit floating in it", M),
        ("Pina Colada", "A cocktail", "Holiday in a glass", M),
        ("Cider", "A drink", "Apples, fermented", M),
        ("Sparkling Water", "A fizzy beverage", "Bubbles without flavour", M),
        ("Latte", "A coffee drink", "Mostly milk", M),
        ("Green Tea", "A hot drink", "Calm and grassy", M),
        ("Ginger Ale", "A fizzy drink", "Settles the stomach", M),
        ("Root Beer", "A fizzy drink", "Tastes like medicine to some", H),
        ("Matcha", "A modern drink", "Bright green powder", H),
        ("Kombucha", "A modern drink", "Alive, technically", H),
        ("Horchata", "A traditional drink", "Sweet, milky and spiced", H),
        ("Turkish Coffee", "A traditional hot drink", "Do not finish the bottom", H),
        ("Bubble Tea", "A modern drink", "Chewy surprises", M),
        ("Sports Drink", "A beverage for athletes", "Colour is the flavour", M),
    ]),

    "clothing": ("Clothing", "\U0001F457", [
        ("T-Shirt", "A clothing item", "The default top", E),
        ("Jeans", "A clothing item", "Blue and everywhere", E),
        ("Jacket", "A clothing item", "For the walk home", E),
        ("Socks", "A clothing item", "One always disappears", E),
        ("Hat", "A clothing item", "Worn on top", E),
        ("Scarf", "A clothing item", "Wrapped around", E),
        ("Dress", "A clothing item", "One piece", E),
        ("Sneakers", "Footwear", "For walking or looking good", E),
        ("Gloves", "A clothing item", "Five fingers each", E),
        ("Pyjamas", "A clothing item", "Only seen at home", E),
        ("Sweater", "A clothing item", "Warm and knitted", E),
        ("Boots", "Footwear", "For bad weather", E),
        ("Suit", "A clothing item", "For serious days", M),
        ("Swimsuit", "A clothing item", "Meant to get wet", M),
        ("Raincoat", "A clothing item", "Keeps the sky out", M),
        ("Hoodie", "A clothing item", "Pull it up and disappear", M),
        ("Belt", "An accessory", "Holds things up", M),
        ("Tie", "An accessory", "A knot with rules", M),
        ("Flip Flops", "Footwear", "Announce your arrival", M),
        ("Sunglasses", "An accessory", "Half disguise", M),
        ("Skirt", "A clothing item", "No legs divided", M),
        ("Uniform", "A clothing type", "Everyone matches", M),
        ("Apron", "A clothing item", "Protects the rest", M),
        ("Blazer", "A clothing item", "Smart but not formal", M),
        ("High Heels", "Footwear", "Height at a cost", M),
        ("Kimono", "A traditional garment", "Wrapped and tied", H),
        ("Poncho", "A clothing item", "One hole for the head", H),
        ("Tuxedo", "A formal garment", "Black tie required", H),
        ("Beanie", "A clothing item", "Warm and slouchy", M),
        ("Cufflinks", "An accessory", "Small and unnecessary", H),
        ("Cardigan", "A clothing item", "Buttons all the way down", H),
    ]),

    "school": ("School & Education", "\U0001F3EB", [
        ("Homework", "A school thing", "School that follows you", E),
        ("Teacher", "A school person", "Explains it again", E),
        ("Exam", "A school event", "Silence and sweating", E),
        ("Blackboard", "A classroom item", "Dust and chalk", E),
        ("Backpack", "A school item", "Heavier every year", E),
        ("Pencil", "A school item", "Mistakes are allowed", E),
        ("Library", "A school place", "Quiet by rule", E),
        ("Recess", "A school moment", "The real lesson", E),
        ("Notebook", "A school item", "Blank then full", E),
        ("Mathematics", "A school subject", "Numbers arguing", E),
        ("History", "A school subject", "Already happened", E),
        ("Chemistry", "A school subject", "Things change form", M),
        ("Report Card", "A school item", "Shown reluctantly", M),
        ("Detention", "A school punishment", "Time you owe", M),
        ("Graduation", "A school event", "Hats in the air", M),
        ("Uniform", "A school item", "Nobody's favourite", M),
        ("School Bus", "A vehicle for students", "Yellow and early", M),
        ("Field Trip", "A school event", "Learning, allegedly", M),
        ("Cafeteria", "A school place", "Trays and queues", M),
        ("Principal", "A school person", "Rarely good news", M),
        ("Calculator", "A school item", "Sometimes forbidden", M),
        ("Whiteboard", "A classroom item", "Wrong pen ruins it", M),
        ("Geography", "A school subject", "Where things are", M),
        ("Biology", "A school subject", "Living things", M),
        ("Diploma", "A school item", "Paper that took years", M),
        ("Substitute Teacher", "A school person", "Nothing gets done", H),
        ("Parent-Teacher Meeting", "A school event", "Two worlds collide", H),
        ("Semester", "A school term", "A chunk of the year", H),
        ("Scholarship", "An education thing", "Someone else pays", H),
        ("Thesis", "An education thing", "Very long and defended", H),
    ]),

    "nature": ("Nature & Weather", "\U0001F326", [
        ("Rain", "A weather type", "The sky lets go", E),
        ("Snow", "A weather type", "Quiet and cold", E),
        ("Rainbow", "A weather event", "After the bad part", E),
        ("Thunder", "A weather sound", "Late to its own light", E),
        ("Lightning", "A weather event", "Bright and brief", E),
        ("Wind", "A weather type", "Felt, never seen", E),
        ("Sun", "In the sky", "Everything depends on it", E),
        ("Moon", "In the sky", "Borrowed light", E),
        ("Cloud", "In the sky", "Shapes for the bored", E),
        ("Fog", "A weather type", "The world shrinks", E),
        ("Ocean", "A natural place", "Mostly unexplored", E),
        ("Mountain", "A natural place", "Up and up", E),
        ("Forest", "A natural place", "Crowded but silent", E),
        ("River", "A natural place", "Always leaving", E),
        ("Desert", "A natural place", "Everything is patient", M),
        ("Volcano", "A natural feature", "Sleeps, then does not", M),
        ("Earthquake", "A natural event", "The ground disagrees", M),
        ("Hurricane", "A weather event", "Calm in the middle", M),
        ("Tornado", "A weather event", "A spinning problem", M),
        ("Waterfall", "A natural feature", "The river gives up", M),
        ("Sunset", "A daily event", "Everyone takes a photo", M),
        ("Glacier", "A natural feature", "Slow but powerful", M),
        ("Island", "A natural place", "Surrounded", M),
        ("Cave", "A natural place", "Dark and old", M),
        ("Frost", "A weather type", "Overnight decoration", M),
        ("Hail", "A weather type", "Rain that hurts", M),
        ("Drought", "A weather event", "Nothing arrives", H),
        ("Avalanche", "A natural event", "Too much at once", H),
        ("Monsoon", "A weather season", "It commits", H),
        ("Eclipse", "A sky event", "Something gets in the way", H),
        ("Tundra", "A natural place", "Frozen and treeless", H),
    ]),
}
