# (word, easy hint, vague hint, difficulty)
E, M, H = "easy", "medium", "hard"

PART1 = {
    "food": ("Food", "\U0001F354", [
        ("Pizza", "Italian food", "Round and shared", E),
        ("Burger", "Fast food", "Stacked in layers", E),
        ("Ice Cream", "A cold dessert", "Melts if you wait", E),
        ("Pasta", "Italian food", "Boiled then sauced", E),
        ("Chocolate", "A sweet treat", "Brown and tempting", E),
        ("Sandwich", "Lunch food", "Two slices and a middle", E),
        ("Popcorn", "Cinema snack", "It pops", E),
        ("Sushi", "Japanese food", "Rolled and raw", E),
        ("Pancakes", "Breakfast food", "Stacked and drizzled", E),
        ("French Fries", "Fast food side", "Golden sticks", E),
        ("Cheese", "A dairy product", "Ages well", E),
        ("Soup", "A warm dish", "Eaten with a spoon", E),
        ("Tacos", "Mexican food", "Folded and filled", M),
        ("Pancake Syrup", "A breakfast topping", "Slow and sweet", H),
        ("Lasagna", "Italian food", "Built in layers", M),
        ("Donut", "A sweet snack", "Has a hole", M),
        ("Cereal", "Breakfast food", "Needs milk", M),
        ("Barbecue", "Cooked outdoors", "Smoke and fire", M),
        ("Curry", "A spicy dish", "Warm and colourful", M),
        ("Salad", "A healthy dish", "Mostly green", M),
        ("Croissant", "French pastry", "Curved and flaky", M),
        ("Pretzel", "A salty snack", "Twisted", M),
        ("Waffle", "Breakfast food", "Full of squares", M),
        ("Cheesecake", "A dessert", "Rich and chilled", M),
        ("Ramen", "Japanese food", "Slurped from a bowl", M),
        ("Guacamole", "Mexican dip", "Green and mashed", H),
        ("Paella", "Spanish food", "One big pan", H),
        ("Tiramisu", "Italian dessert", "Coffee and cream", H),
        ("Hummus", "A dip", "Beige and creamy", H),
        ("Pad Thai", "A noodle dish from Asia", "Bought from a street cart", H),
        ("Baklava", "A sweet pastry", "Sticky and layered", H),
        ("Kebab", "Street food", "Off the skewer", M),
    ]),

    "sports": ("Sports", "⚽", [
        ("Football", "A sport played with a ball", "Eleven a side", E),
        ("Basketball", "A sport played with a ball", "Aim high", E),
        ("Tennis", "A racket sport", "Back and forth", E),
        ("Swimming", "A water sport", "Lane by lane", E),
        ("Running", "An athletics event", "One foot after the other", E),
        ("Boxing", "A combat sport", "Two in a square", E),
        ("Cycling", "A sport on wheels", "Two circles turning", E),
        ("Volleyball", "A sport played with a ball", "Over the net", E),
        ("Golf", "A club sport", "Very small target", E),
        ("Skiing", "A winter sport", "Downhill in the cold", E),
        ("Baseball", "An American sport", "Swing and run", M),
        ("Ice Hockey", "A winter team sport", "Fast and frozen", M),
        ("Table Tennis", "An indoor racket sport", "Tiny and quick", M),
        ("Surfing", "A water sport", "Wait for the right moment", M),
        ("Gymnastics", "An Olympic sport", "Balance and flight", M),
        ("Wrestling", "A combat sport", "Close contact", M),
        ("Rugby", "A team contact sport", "Backwards passes", M),
        ("Skateboarding", "A street sport", "Four small wheels", M),
        ("Marathon", "A running event", "Very long", M),
        ("Archery", "A target sport", "Steady hands", M),
        ("Formula 1", "A motorsport", "Very loud circles", M),
        ("Bowling", "An indoor sport", "Knock them all down", M),
        ("Climbing", "An outdoor sport", "Only up", M),
        ("Fencing", "A combat sport", "Polite duel", H),
        ("Handball", "A team sport", "Throw, not kick", H),
        ("Water Polo", "A pool sport", "Tiring and wet", H),
        ("Curling", "A winter sport", "Sweeping on ice", H),
        ("Badminton", "A racket sport", "Feathers in the air", M),
        ("Triathlon", "A multi-sport race", "Three in a row", H),
        ("Snowboarding", "A winter sport", "Sideways downhill", M),
    ]),

    "objects": ("Everyday Objects", "\U0001F3E0", [
        ("Toothbrush", "A bathroom item", "Twice a day", E),
        ("Umbrella", "Used in bad weather", "Opens above you", E),
        ("Pillow", "Found in a bedroom", "Soft and quiet", E),
        ("Mirror", "Found in a bathroom", "Gives nothing back", E),
        ("Keys", "Carried in a pocket", "Small but important", E),
        ("Chair", "A piece of furniture", "You use it sitting down", E),
        ("Clock", "Tells you something", "Never stops", E),
        ("Backpack", "Something you carry", "Straps over both shoulders", E),
        ("Towel", "A bathroom item", "Gets wet on purpose", E),
        ("Scissors", "A cutting tool", "Two blades, one job", E),
        ("Candle", "Makes light", "Shorter over time", M),
        ("Wallet", "Carried in a pocket", "Holds the important cards", M),
        ("Broom", "A cleaning tool", "Sweeps things away", M),
        ("Ladder", "A household tool", "Helps you reach", M),
        ("Sunglasses", "Worn on the face", "For bright days", M),
        ("Blanket", "Found in a bedroom", "Warm and heavy", M),
        ("Toaster", "A kitchen appliance", "Pops up", M),
        ("Vacuum Cleaner", "A household appliance", "Loud and hungry", M),
        ("Hairdryer", "A bathroom appliance", "Warm wind", M),
        ("Doorbell", "Found at an entrance", "Announces someone", M),
        ("Stapler", "An office item", "Holds paper together", M),
        ("Suitcase", "Used when travelling", "Packed and rolled", M),
        ("Flashlight", "Makes light", "Only when you need it", M),
        ("Corkscrew", "A kitchen tool", "Twists to open", H),
        ("Thermometer", "A measuring tool", "Tells you a number", H),
        ("Fire Extinguisher", "A safety item", "Hopefully never used", H),
        ("Tape Measure", "A DIY tool", "Rolls back on itself", H),
        ("Nail Clippers", "A grooming tool", "Small and sharp", H),
        ("Ironing Board", "A laundry item", "Folds away", H),
        ("Watering Can", "A garden item", "Gentle rain", M),
    ]),

    "movies": ("Popular Movies", "\U0001F3AC", [
        ("Titanic", "A famous movie", "It ends underwater", E),
        ("Frozen", "An animated movie", "Very cold, very catchy", E),
        ("Jurassic Park", "A famous movie", "Very old animals", E),
        ("The Lion King", "An animated movie", "A young ruler", E),
        ("Harry Potter", "A fantasy movie", "School with a twist", E),
        ("Avatar", "A science fiction movie", "Blue and tall", E),
        ("Toy Story", "An animated movie", "They move when you leave", E),
        ("Shrek", "An animated movie", "Green and grumpy", E),
        ("Finding Nemo", "An animated movie", "A long swim", E),
        ("Star Wars", "A science fiction movie", "Family drama in space", E),
        ("The Godfather", "A classic movie", "Family business", M),
        ("Jaws", "A thriller movie", "Do not go in the water", M),
        ("Forrest Gump", "A classic movie", "A very long walk", M),
        ("The Matrix", "A science fiction movie", "Choose a colour", M),
        ("Inception", "A science fiction movie", "Sleep is complicated", M),
        ("Rocky", "A sports movie", "Stairs and gloves", M),
        ("Home Alone", "A holiday movie", "Forgotten on purpose", M),
        ("Pirates of the Caribbean", "An adventure movie", "Sea and gold", M),
        ("Despicable Me", "An animated movie", "Small yellow helpers", M),
        ("The Avengers", "A superhero movie", "Too many main characters", M),
        ("Back to the Future", "A science fiction movie", "A very fast car", M),
        ("Gladiator", "A historical movie", "Sand and swords", M),
        ("Interstellar", "A science fiction movie", "Time is expensive", H),
        ("Pulp Fiction", "A cult classic movie", "Told out of order", H),
        ("The Shining", "A horror movie", "A very quiet hotel", H),
        ("Casablanca", "A classic movie", "Black and white goodbye", H),
        ("Parasite", "An award-winning movie", "Two households", H),
        ("La La Land", "A musical movie", "Dancing and disappointment", H),
        ("Fight Club", "A cult classic movie", "Do not talk about it", H),
        ("Up", "An animated movie", "Balloons and a house", M),
    ]),

    "people": ("Popular People", "\U0001F464", [
        ("Albert Einstein", "A famous scientist", "Hair and equations", E),
        ("Michael Jackson", "A famous singer", "One glove", E),
        ("Leonardo da Vinci", "A famous artist", "Painter and inventor", E),
        ("Charlie Chaplin", "A famous actor", "Silent and funny", E),
        ("Cleopatra", "A historical ruler", "Ancient royalty", E),
        ("William Shakespeare", "A famous writer", "Old English drama", E),
        ("Elvis Presley", "A famous singer", "The hips", E),
        ("Marilyn Monroe", "A famous actress", "The white dress", E),
        ("Nelson Mandela", "A famous leader", "Prison then presidency", E),
        ("Steve Jobs", "A famous businessman", "Black turtleneck", E),
        ("Isaac Newton", "A famous scientist", "Something fell", M),
        ("Marie Curie", "A famous scientist", "Glowing research", M),
        ("Napoleon", "A historical leader", "Short and ambitious", M),
        ("Mozart", "A famous composer", "Started very young", M),
        ("Vincent van Gogh", "A famous painter", "Stars and one ear", M),
        ("Walt Disney", "A famous creator", "Built a kingdom", M),
        ("Oprah Winfrey", "A famous TV host", "You get a car", M),
        ("Beyonce", "A famous singer", "Formation", M),
        ("Julius Caesar", "A historical leader", "Betrayed by friends", M),
        ("Bill Gates", "A famous businessman", "Windows", M),
        ("Frida Kahlo", "A famous painter", "Self portraits", H),
        ("Galileo", "A famous scientist", "Looked up and was punished", H),
        ("Amelia Earhart", "A famous pilot", "Never landed", H),
        ("Pablo Picasso", "A famous painter", "Faces from two sides", M),
        ("Mahatma Gandhi", "A famous leader", "Won without fighting", M),
        ("Ludwig van Beethoven", "A famous composer", "Could not hear the end", H),
        ("Salvador Dali", "A famous painter", "Melting time", H),
        ("Alfred Hitchcock", "A famous director", "Suspense and birds", H),
        ("Neil Armstrong", "A famous astronaut", "One small step", M),
        ("Coco Chanel", "A famous designer", "The little black dress", H),
    ]),
}
