E, M, H = "easy", "medium", "hard"

PART2 = {
    "athletes": ("Popular Athletes", "\U0001F3C6", [
        ("Cristiano Ronaldo", "A famous footballer", "Never tired of himself", E),
        ("Lionel Messi", "A famous footballer", "Small and unstoppable", E),
        ("Michael Jordan", "A famous basketball player", "The number 23", E),
        ("Serena Williams", "A famous tennis player", "Power on court", E),
        ("Usain Bolt", "A famous sprinter", "Nobody was close", E),
        ("Muhammad Ali", "A famous boxer", "Float and sting", E),
        ("LeBron James", "A famous basketball player", "Still going", E),
        ("Roger Federer", "A famous tennis player", "Very polite winner", E),
        ("Tiger Woods", "A famous golfer", "Red shirt on Sunday", E),
        ("Pele", "A famous footballer", "The old king", M),
        ("Rafael Nadal", "A famous tennis player", "Loves the clay", M),
        ("Novak Djokovic", "A famous tennis player", "Bends but never breaks", M),
        ("Kobe Bryant", "A famous basketball player", "The mamba", M),
        ("Neymar", "A famous footballer", "Falls dramatically", M),
        ("Lewis Hamilton", "A famous racing driver", "Very fast circles", M),
        ("Michael Phelps", "A famous swimmer", "A wall of medals", M),
        ("Maradona", "A famous footballer", "A suspicious goal", M),
        ("Simone Biles", "A famous gymnast", "Defies gravity", M),
        ("Kylian Mbappe", "A famous footballer", "Too quick", M),
        ("Conor McGregor", "A famous fighter", "Talks first", M),
        ("Wayne Gretzky", "A famous hockey player", "The great one", H),
        ("Zinedine Zidane", "A famous footballer", "A famous headbutt", M),
        ("Shaquille O'Neal", "A famous basketball player", "Broke the hoops", M),
        ("Ayrton Senna", "A famous racing driver", "Rain was his weather", H),
        ("Carl Lewis", "A famous athlete", "Ran and jumped", H),
        ("Nadia Comaneci", "A famous gymnast", "A perfect number", H),
        ("Eliud Kipchoge", "A famous runner", "Under two hours", H),
        ("Katie Ledecky", "A famous swimmer", "Long and lonely lanes", H),
        ("Magic Johnson", "A famous basketball player", "Passes you did not see", H),
        ("Valentino Rossi", "A famous motorcycle racer", "Yellow and 46", H),
    ]),

    "places": ("Popular Places", "\U0001F30D", [
        ("Eiffel Tower", "A famous landmark", "Iron and romantic", E),
        ("Great Wall of China", "A famous landmark", "Very long defence", E),
        ("Pyramids of Giza", "An ancient landmark", "Very old triangles", E),
        ("Statue of Liberty", "A famous landmark", "A gift that stayed", E),
        ("Colosseum", "An ancient landmark", "Old entertainment", E),
        ("Big Ben", "A famous landmark", "Tells the time loudly", E),
        ("Taj Mahal", "A famous landmark", "Built out of grief", E),
        ("Grand Canyon", "A natural wonder", "Water was patient", E),
        ("Niagara Falls", "A natural wonder", "Loud water", E),
        ("Mount Everest", "A famous peak", "The highest queue", E),
        ("Sahara Desert", "A natural place", "Very dry and very big", M),
        ("Amazon Rainforest", "A natural place", "Green and loud", M),
        ("Stonehenge", "An ancient landmark", "Nobody agrees why", M),
        ("Machu Picchu", "An ancient landmark", "High and hidden", M),
        ("Sydney Opera House", "A famous building", "Shells by the water", M),
        ("Leaning Tower of Pisa", "A famous landmark", "A construction mistake", M),
        ("Times Square", "A famous city spot", "Never dark", M),
        ("Louvre", "A famous museum", "Glass and a small painting", M),
        ("Mount Fuji", "A famous peak in Asia", "Painted a thousand times", M),
        ("Golden Gate Bridge", "A famous crossing", "Orange and foggy", M),
        ("Santorini", "A holiday island", "White and blue", M),
        ("Petra", "An ancient landmark", "Carved into rock", H),
        ("Angkor Wat", "An ancient temple", "Swallowed by jungle", H),
        ("Chichen Itza", "An ancient landmark", "Steps and shadows", H),
        ("Victoria Falls", "A natural wonder", "Smoke that thunders", H),
        ("Dead Sea", "A natural place", "You cannot sink", H),
        ("Mount Rushmore", "A famous landmark", "Faces in stone", M),
        ("Buckingham Palace", "A famous building", "Guards who do not move", M),
        ("Northern Lights", "A natural wonder", "The sky performs", M),
        ("Serengeti", "A natural place", "Everything migrates", H),
    ]),

    "animals": ("Animals", "\U0001F436", [
        ("Dog", "A pet", "Very loyal", E),
        ("Cat", "A pet", "Pretends not to care", E),
        ("Elephant", "A large animal", "Never forgets", E),
        ("Lion", "A wild animal", "Sleeps most of the day", E),
        ("Penguin", "A cold-climate animal", "Dressed formally", E),
        ("Dolphin", "A sea animal", "Too clever", E),
        ("Horse", "A farm animal", "You can ride it", E),
        ("Monkey", "A jungle animal", "Copies you", E),
        ("Giraffe", "A tall animal", "Great view", E),
        ("Shark", "A sea animal", "Bad reputation", E),
        ("Snake", "A reptile", "No legs required", E),
        ("Rabbit", "A small animal", "Fast and nervous", E),
        ("Kangaroo", "An Australian animal", "Built-in pocket", M),
        ("Owl", "A bird", "Works nights", M),
        ("Octopus", "A sea animal", "Eight solutions", M),
        ("Panda", "A rare animal", "One food only", M),
        ("Crocodile", "A reptile", "Patient and still", M),
        ("Bee", "An insect", "Sweet but armed", M),
        ("Wolf", "A wild animal", "Better in a group", M),
        ("Camel", "A desert animal", "Plans ahead", M),
        ("Hedgehog", "A small animal", "Rolls up", M),
        ("Flamingo", "A bird", "Stands on one leg", M),
        ("Chameleon", "A reptile", "Changes its mind", M),
        ("Sloth", "A jungle animal", "In no hurry", M),
        ("Platypus", "An unusual animal", "Seems like a mistake", H),
        ("Meerkat", "A desert animal", "Always on watch", H),
        ("Jellyfish", "A sea animal", "No brain, still wins", H),
        ("Peacock", "A bird", "Shows off", M),
        ("Narwhal", "A sea animal", "One long tooth", H),
        ("Axolotl", "An unusual animal", "Never grows up", H),
    ]),

    "vehicles": ("Vehicles", "\U0001F697", [
        ("Car", "A road vehicle", "Four wheels, one owner", E),
        ("Bicycle", "A road vehicle", "Powered by legs", E),
        ("Airplane", "An air vehicle", "Very fast queue", E),
        ("Bus", "Public transport", "Everyone shares it", E),
        ("Train", "Public transport", "Follows a line", E),
        ("Motorcycle", "A road vehicle", "Two wheels and noise", E),
        ("Boat", "A water vehicle", "Needs no road", E),
        ("Helicopter", "An air vehicle", "Rises straight up", E),
        ("Truck", "A large road vehicle", "Carries the rest", E),
        ("Scooter", "A small vehicle", "Stand and go", E),
        ("Ambulance", "An emergency vehicle", "You hear it first", M),
        ("Fire Truck", "An emergency vehicle", "Red and loud", M),
        ("Submarine", "A water vehicle", "Goes down instead", M),
        ("Tractor", "A farm vehicle", "Slow on purpose", M),
        ("Taxi", "Public transport", "Costs by distance", M),
        ("Skateboard", "A small vehicle", "No brakes", M),
        ("Rocket", "A space vehicle", "One-way for most", M),
        ("Hot Air Balloon", "An air vehicle", "You do not steer", M),
        ("Tram", "Public transport", "City rails", M),
        ("Ferry", "A water vehicle", "Carries cars too", M),
        ("Limousine", "A luxury vehicle", "Unnecessarily long", M),
        ("Snowmobile", "A winter vehicle", "For where roads stop", H),
        ("Gondola", "A water vehicle", "Someone else pushes", H),
        ("Segway", "A small vehicle", "Balance is the point", H),
        ("Jet Ski", "A water vehicle", "Holiday noise", M),
        ("Cable Car", "A mountain vehicle", "Hangs there", M),
        ("Forklift", "A work vehicle", "Lifts more than it looks", H),
        ("Hovercraft", "An unusual vehicle", "Neither road nor sea", H),
        ("Sled", "A winter vehicle", "Only goes downhill", M),
        ("Zeppelin", "An air vehicle", "Slow and enormous", H),
    ]),

    "games": ("Video Games", "\U0001F3AE", [
        ("Minecraft", "A video game", "Everything is a cube", E),
        ("Fortnite", "A video game", "Last one standing", E),
        ("Tetris", "A classic game", "Falling shapes", E),
        ("Pac-Man", "A classic game", "Eat and run", E),
        ("Super Mario", "A video game", "Jumping plumber", E),
        ("FIFA", "A sports video game", "Digital football", E),
        ("Angry Birds", "A mobile game", "Aim and launch", E),
        ("Pokemon", "A video game", "Collect them all", E),
        ("Candy Crush", "A mobile game", "Match three", E),
        ("Roblox", "A video game", "A game about games", E),
        ("Call of Duty", "A shooter game", "Always another war", M),
        ("Grand Theft Auto", "A video game", "Crime and driving", M),
        ("The Sims", "A life simulation game", "Chores, but fun", M),
        ("Zelda", "An adventure game", "Rescue and explore", M),
        ("Among Us", "A social game", "Someone is lying", M),
        ("Mario Kart", "A racing game", "Friendship ends here", M),
        ("Sonic", "A classic game", "Blue and quick", M),
        ("Counter-Strike", "A shooter game", "Plant or defuse", M),
        ("League of Legends", "A video game", "Five lanes of arguing", M),
        ("Street Fighter", "A one-on-one arcade game", "Combo buttons", M),
        ("Space Invaders", "A classic game", "They come down slowly", M),
        ("Assassin's Creed", "A video game", "History with hoods", M),
        ("Animal Crossing", "A video game", "Calm and endless", M),
        ("Dark Souls", "A video game", "You will die again", H),
        ("Portal", "A puzzle game", "Two holes, one idea", H),
        ("Overwatch", "A shooter game", "Pick a hero", H),
        ("Red Dead Redemption", "A video game", "Horses and regret", H),
        ("Elden Ring", "A video game", "Big, lonely and cruel", H),
        ("Guitar Hero", "A music game", "Plastic instrument", H),
        ("Doom", "A classic shooter", "Corridors and demons", M),
    ]),

    "tech": ("Technology", "\U0001F4F1", [
        ("Smartphone", "A modern device", "Everyone checks it", E),
        ("Laptop", "A computer", "Folds shut", E),
        ("Wi-Fi", "Something in every home", "Invisible but essential", E),
        ("Headphones", "An audio device", "Private sound", E),
        ("Camera", "A device", "Keeps the moment", E),
        ("Television", "A home device", "The old main screen", E),
        ("Keyboard", "A computer part", "Many small buttons", E),
        ("Bluetooth", "A connection type", "Short range pairing", E),
        ("USB Stick", "A storage device", "Always the wrong way up", E),
        ("Robot", "A machine", "Does it for you", E),
        ("Smartwatch", "A wearable device", "Tells you to stand", M),
        ("Drone", "A flying device", "Views from above", M),
        ("Printer", "An office device", "Never works first time", M),
        ("GPS", "A navigation tool", "Knows where you are", M),
        ("Password", "A security thing", "Forgotten weekly", M),
        ("Cloud Storage", "A tech service", "It is just someone's computer", M),
        ("Artificial Intelligence", "A modern technology", "Answers confidently", M),
        ("Video Call", "A way to communicate", "You are on mute", M),
        ("Touchscreen", "A device feature", "Fingerprints included", M),
        ("Electric Car", "A modern vehicle", "Quiet and plugged in", M),
        ("Virtual Reality", "A modern technology", "Wear it to leave", M),
        ("QR Code", "A modern symbol", "Point your camera", M),
        ("Search Engine", "An internet tool", "Everyone's first question", M),
        ("Emoji", "A digital thing", "Feelings, compressed", M),
        ("3D Printer", "A modern machine", "Builds in layers", H),
        ("Satellite", "A space technology", "Circles and listens", H),
        ("Fingerprint Scanner", "A security feature", "Only you fit", H),
        ("Solar Panel", "An energy technology", "Needs a good day", H),
        ("Server", "A computer", "Somewhere in a cold room", H),
        ("Firewall", "A security technology", "Decides who enters", H),
    ]),
}
