E, M, H = "easy", "medium", "hard"

PART4 = {
    "vacation": ("Vacation Destinations", "\U0001F3D6", [
        ("Beach", "A holiday place", "Sand gets everywhere", E),
        ("Hotel", "A holiday place", "Someone makes the bed", E),
        ("Cruise", "A type of holiday", "The hotel moves", E),
        ("Camping", "A type of holiday", "Nature, uncomfortably", E),
        ("Ski Resort", "A winter holiday place", "Cold and expensive", E),
        ("Maldives", "A holiday destination", "Water in every direction", E),
        ("Hawaii", "A holiday destination", "Flowers and volcanoes", E),
        ("Theme Park", "A holiday place", "Queue then scream", E),
        ("Road Trip", "A type of holiday", "The route is the point", E),
        ("Bali", "A holiday destination", "Temples and surfing", M),
        ("Safari", "A type of holiday", "Watch, do not touch", M),
        ("Ibiza", "A holiday destination", "Sleep is optional", M),
        ("Swimming Pool", "A holiday feature", "Blue and crowded", E),
        ("Backpacking", "A type of holiday", "Everything you own, on your shoulders", M),
        ("Cabin", "A holiday place", "Wood and quiet", M),
        ("All-Inclusive", "A holiday type", "Paid for in advance", M),
        ("Airport", "Part of travelling", "Waiting, professionally", M),
        ("Souvenir", "A holiday item", "Regretted at home", M),
        ("Cancun", "A holiday destination", "Turquoise and busy", M),
        ("Amalfi Coast", "A holiday destination", "Cliffs and lemons", M),
        ("Northern Ireland", "A travel destination", "Green and windswept", H),
        ("Yosemite", "A national park", "Granite and waterfalls", H),
        ("Patagonia", "A travel destination", "Wind at the end", H),
        ("Hostel", "A holiday place", "Cheap and social", M),
        ("Sunburn", "A holiday problem", "Regret you can feel", M),
        ("Passport", "A travel item", "The photo is terrible", M),
        ("Snorkelling", "A holiday activity", "Look down, breathe up", M),
        ("Glamping", "A holiday type", "Nature with a mattress", H),
        ("Mount Kilimanjaro", "A travel destination", "Walk up slowly", H),
        ("Lake District", "A travel destination", "Water and walking boots", H),
    ]),

    "jobs": ("Jobs & Professions", "\U0001F454", [
        ("Doctor", "A profession", "Asks where it hurts", E),
        ("Teacher", "A profession", "Explains again", E),
        ("Firefighter", "A profession", "Runs toward it", E),
        ("Chef", "A profession", "Hot and shouting", E),
        ("Police Officer", "A profession", "Asks the questions", E),
        ("Pilot", "A profession", "Announces the weather", E),
        ("Nurse", "A profession", "The one who actually helps", E),
        ("Farmer", "A profession", "Up before everyone", E),
        ("Dentist", "A profession", "Nobody looks forward to it", E),
        ("Lawyer", "A profession", "Reads the small print", E),
        ("Engineer", "A profession", "Makes it work", E),
        ("Photographer", "A profession", "Waits for the light", M),
        ("Journalist", "A profession", "Asks the awkward question", M),
        ("Architect", "A profession", "Draws before building", M),
        ("Barber", "A profession", "Short conversation, shorter hair", M),
        ("Mechanic", "A profession", "Diagnoses by sound", M),
        ("Scientist", "A profession", "Mostly failing on purpose", M),
        ("Accountant", "A profession", "Numbers must agree", M),
        ("Electrician", "A profession", "Do not touch that", M),
        ("Waiter", "A profession", "Remembers your order", M),
        ("Librarian", "A profession", "Keeps it quiet", M),
        ("Plumber", "A profession", "Arrives when it is too late", M),
        ("Veterinarian", "A profession", "The patient cannot explain", M),
        ("Translator", "A profession", "In between two people", M),
        ("Astronaut", "A profession", "Very few positions", M),
        ("Lifeguard", "A profession", "Watches and waits", M),
        ("Referee", "A profession", "Everyone disagrees", M),
        ("Archaeologist", "A profession", "Digs for old things", H),
        ("Air Traffic Controller", "A profession", "No room for error", H),
        ("Sommelier", "A profession", "Knows the year", H),
        ("Actuary", "A profession", "Predicts the unlikely", H),
        ("Zookeeper", "A profession", "Feeds the unusual", H),
    ]),

    "hobbies": ("Hobbies", "\U0001F3A8", [
        ("Painting", "A creative hobby", "Colour on a surface", E),
        ("Reading", "A quiet hobby", "One page at a time", E),
        ("Gardening", "An outdoor hobby", "Patience required", E),
        ("Cooking", "A home hobby", "Tasted before finished", E),
        ("Photography", "A creative hobby", "Freeze the moment", E),
        ("Fishing", "An outdoor hobby", "Mostly waiting", E),
        ("Dancing", "An active hobby", "Move to the sound", E),
        ("Singing", "A musical hobby", "Best in the shower", E),
        ("Hiking", "An outdoor hobby", "Walking with a view", E),
        ("Drawing", "A creative hobby", "Lines first", E),
        ("Knitting", "A crafting hobby", "Loop after loop", M),
        ("Chess", "An indoor hobby", "Think before touching", M),
        ("Puzzles", "An indoor hobby", "The edges first", M),
        ("Baking", "A home hobby", "Measure exactly", M),
        ("Collecting", "A hobby", "Never quite complete", M),
        ("Yoga", "A wellness hobby", "Breathe and hold", M),
        ("Camping", "An outdoor hobby", "Sleep outside on purpose", M),
        ("Woodworking", "A crafting hobby", "Measure twice", M),
        ("Birdwatching", "An outdoor hobby", "Quiet and hopeful", M),
        ("Journaling", "A quiet hobby", "For your eyes only", M),
        ("Pottery", "A crafting hobby", "Spins while you shape it", M),
        ("Board Games", "An indoor hobby", "Friendships tested", M),
        ("Karaoke", "A social hobby", "Confidence over talent", M),
        ("Origami", "A crafting hobby", "Folds, no cutting", H),
        ("Calligraphy", "A creative hobby", "Slow, beautiful writing", H),
        ("Astronomy", "A night hobby", "Looking very far back", H),
        ("Scrapbooking", "A crafting hobby", "Memories with glue", H),
        ("Geocaching", "An outdoor hobby", "A hidden box somewhere", H),
        ("Model Building", "A crafting hobby", "Small and patient", H),
        ("Rollerblading", "An active hobby", "Wheels on your feet", M),
    ]),

    "tvshows": ("TV Shows", "\U0001F3AD", [
        ("Friends", "A famous TV show", "Six people, one sofa", E),
        ("The Simpsons", "An animated TV show", "Yellow and endless", E),
        ("Game of Thrones", "A famous TV show", "Nobody is safe", E),
        ("Stranger Things", "A popular TV show", "The eighties went wrong", E),
        ("SpongeBob", "An animated TV show", "Lives underwater", E),
        ("Breaking Bad", "A famous TV show", "A teacher changes career", E),
        ("The Office", "A comedy TV show", "The camera is watching", E),
        ("Tom and Jerry", "An animated TV show", "No dialogue needed", E),
        ("Pokemon", "An animated TV show", "Gotta catch them", E),
        ("Sherlock", "A crime TV show", "Notices everything", M),
        ("Money Heist", "A popular TV show", "Red suits and masks", M),
        ("The Crown", "A drama TV show", "Real people, dramatised", M),
        ("Squid Game", "A popular TV show", "Children's play, deadly stakes", M),
        ("Peaky Blinders", "A drama TV show", "Hats and threats", M),
        ("Big Bang Theory", "A comedy TV show", "Clever and awkward", M),
        ("Rick and Morty", "An animated TV show", "Science and chaos", M),
        ("The Mandalorian", "A science fiction show", "Helmet stays on", M),
        ("How I Met Your Mother", "A comedy TV show", "A very long story", M),
        ("Grey's Anatomy", "A drama TV show", "Hospital and heartbreak", M),
        ("Black Mirror", "A drama TV show", "Technology goes wrong", M),
        ("MasterChef", "A reality TV show", "Judged by taste", M),
        ("Top Gear", "A reality TV show", "Cars and arguments", M),
        ("Family Guy", "An animated TV show", "Interrupted by memories", M),
        ("Narcos", "A drama TV show", "Powder and power", H),
        ("The Witcher", "A fantasy TV show", "Silver hair, monsters", M),
        ("Chernobyl", "A drama TV show", "Something invisible", H),
        ("Suits", "A drama TV show", "Sharp clothes, sharper talk", H),
        ("Dexter", "A crime TV show", "Works both sides", H),
        ("Lost", "A famous TV show", "Nobody understood the ending", H),
        ("Downton Abbey", "A drama TV show", "Servants and their masters", H),
    ]),

    "superheroes": ("Superheroes", "\U0001F9B8", [
        ("Superman", "A fictional hero", "Only one weakness", E),
        ("Batman", "A fictional hero", "No powers, just money", E),
        ("Spider-Man", "A fictional hero", "Sticks to walls", E),
        ("Iron Man", "A fictional hero", "The suit is the power", E),
        ("Wonder Woman", "A fictional hero", "Truth by rope", E),
        ("Hulk", "A fictional hero", "Anger management", E),
        ("Captain America", "A fictional hero", "Round shield", E),
        ("Thor", "A fictional hero", "Only he can lift it", E),
        ("Black Panther", "A fictional hero", "A hidden kingdom", E),
        ("Flash", "A fictional hero", "Arrives before you finish", E),
        ("Wolverine", "A fictional hero", "Heals and cuts", M),
        ("Deadpool", "A fictional hero", "Talks to you", M),
        ("Aquaman", "A fictional hero", "Rules the water", M),
        ("Doctor Strange", "A fictional hero", "Magic and portals", M),
        ("Black Widow", "A fictional hero", "No powers, all training", M),
        ("Green Lantern", "A fictional hero", "Willpower and a ring", M),
        ("Ant-Man", "A fictional hero", "Size is the trick", M),
        ("Catwoman", "A fictional character", "Not quite a hero", M),
        ("Joker", "A fictional villain", "Laughs at the wrong time", M),
        ("Thanos", "A fictional villain", "Believes in balance", M),
        ("Loki", "A fictional character", "Never the same twice", M),
        ("Captain Marvel", "A fictional hero", "Glows and flies", M),
        ("Hawkeye", "A fictional hero", "Brought a bow to a war", M),
        ("Robin", "A fictional hero", "Always second", M),
        ("Groot", "A fictional character", "Three words only", M),
        ("Magneto", "A fictional villain", "Metal obeys", H),
        ("Silver Surfer", "A fictional hero", "Rides through space", H),
        ("Storm", "A fictional hero", "Weather on request", H),
        ("Venom", "A fictional character", "Wears its host", H),
        ("Professor X", "A fictional hero", "Reads the room, literally", H),
    ]),
}
