E, M, H = "easy", "medium", "hard"

PART3 = {
    "music": ("Music", "\U0001F3B5", [
        ("Guitar", "A musical instrument", "Six strings", E),
        ("Piano", "A musical instrument", "Black and white", E),
        ("Drums", "A musical instrument", "Loudest in the room", E),
        ("Violin", "A musical instrument", "Played with a bow", E),
        ("Microphone", "Music equipment", "Makes you louder", E),
        ("Concert", "A music event", "Everyone stands", E),
        ("Rock", "A music genre", "Loud guitars", E),
        ("Rap", "A music genre", "Words come first", E),
        ("Choir", "A group of singers", "Many voices, one sound", E),
        ("Headliner", "A music event term", "Plays last on purpose", M),
        ("Jazz", "A music genre", "Rules are optional", M),
        ("Opera", "A music style", "Dramatic and long", M),
        ("Karaoke", "A music activity", "Courage required", M),
        ("Flute", "A musical instrument", "Sideways and airy", M),
        ("Saxophone", "A musical instrument", "Smooth and brassy", M),
        ("Trumpet", "A musical instrument", "Bright and brassy", M),
        ("DJ", "A music person", "Never plays a note", M),
        ("Vinyl Record", "Music media", "Old but back again", M),
        ("Festival", "A music event", "Mud and wristbands", M),
        ("Harmonica", "A musical instrument", "Fits in a pocket", M),
        ("Reggae", "A music genre", "Off the beat", M),
        ("Classical", "A music genre", "Written long ago", M),
        ("Ukulele", "A musical instrument", "Small and cheerful", M),
        ("Accordion", "A musical instrument", "Squeezed to play", H),
        ("Bagpipes", "A musical instrument", "Heard from far away", H),
        ("Conductor", "A music person", "Waves and is obeyed", H),
        ("Metronome", "Music equipment", "Never speeds up", H),
        ("Encore", "A concert moment", "The planned surprise", H),
        ("Cello", "A musical instrument", "Deep and seated", M),
        ("Beatbox", "A music skill", "Instruments not included", H),
    ]),

    "books": ("Books", "\U0001F4DA", [
        ("Harry Potter", "A famous book series", "School with a secret", E),
        ("The Hobbit", "A fantasy book", "A very long walk", E),
        ("Romeo and Juliet", "A classic play", "Bad communication", E),
        ("The Little Prince", "A famous book", "Small planet, big lesson", E),
        ("Dracula", "A classic novel", "Avoid at night", E),
        ("Sherlock Holmes", "A famous detective series", "Small details matter", E),
        ("Alice in Wonderland", "A classic book", "Nothing makes sense", E),
        ("Robinson Crusoe", "A classic novel", "Alone for too long", M),
        ("The Lord of the Rings", "A fantasy series", "Return the jewellery", E),
        ("Frankenstein", "A classic novel", "The creator is the problem", M),
        ("The Hunger Games", "A popular book series", "Televised survival", M),
        ("1984", "A classic novel", "Someone is watching", M),
        ("Pride and Prejudice", "A classic novel", "Manners and money", M),
        ("Moby Dick", "A classic novel", "An obsession at sea", M),
        ("Treasure Island", "A classic adventure", "X marks it", M),
        ("The Diary of Anne Frank", "A famous wartime book", "Written in hiding", M),
        ("Don Quixote", "A classic novel", "Fighting the wrong enemy", H),
        ("The Great Gatsby", "A classic novel", "Parties and longing", M),
        ("Animal Farm", "A classic novel", "Power changes hands", M),
        ("War and Peace", "A classic novel", "Famously heavy", M),
        ("The Odyssey", "An ancient epic", "The long way home", H),
        ("Crime and Punishment", "A classic novel", "Guilt does the work", H),
        ("Les Miserables", "A classic novel", "Bread and revolution", H),
        ("The Catcher in the Rye", "A classic novel", "Everyone is fake", H),
        ("Dune", "A science fiction novel", "Sand and politics", M),
        ("The Da Vinci Code", "A popular thriller", "Art hides answers", M),
        ("Anna Karenina", "A classic novel", "Trains and heartbreak", H),
        ("Charlotte's Web", "A children's book", "A friendship in a barn", M),
        ("The Jungle Book", "A children's classic", "Raised by others", M),
        ("Encyclopedia", "A type of book", "Nobody reads it all", M),
    ]),

    "brands": ("Companies & Brands", "\U0001F3E2", [
        ("Coca-Cola", "A famous brand", "Red and fizzy", E),
        ("Nike", "A sportswear brand", "Just a tick", E),
        ("Apple", "A technology brand", "Fruit and phones", E),
        ("McDonald's", "A fast food brand", "Golden arches", E),
        ("Google", "A technology brand", "The first place you ask", E),
        ("Adidas", "A sportswear brand", "Three lines", E),
        ("Netflix", "An entertainment brand", "Still watching?", E),
        ("Lego", "A toy brand", "Painful underfoot", E),
        ("Ferrari", "A car brand", "Loud and red", E),
        ("Amazon", "An online brand", "It arrives tomorrow", E),
        ("Samsung", "A technology brand", "The other phone", E),
        ("Starbucks", "A coffee brand", "Your name, misspelled", M),
        ("IKEA", "A furniture brand", "Some assembly required", M),
        ("Toyota", "A car brand", "Reliably boring", M),
        ("Disney", "An entertainment brand", "Owns your childhood", M),
        ("YouTube", "An online brand", "Skip ad in five", M),
        ("Spotify", "A music brand", "Your year, summarised", M),
        ("Tesla", "A car brand", "Plugged in and opinionated", M),
        ("Gucci", "A fashion brand", "Expensive on purpose", M),
        ("Rolex", "A watch brand", "Tells more than time", M),
        ("PlayStation", "A gaming brand", "Four symbols", M),
        ("Microsoft", "A technology brand", "Behind most offices", M),
        ("Pepsi", "A drink brand", "Always second", M),
        ("Instagram", "A social brand", "Squares of the best day", M),
        ("Uber", "A service brand", "Someone else drives", M),
        ("Red Bull", "A drink brand", "Wings, allegedly", M),
        ("Lamborghini", "A car brand", "Doors open the wrong way", M),
        ("Chanel", "A fashion brand", "Two facing letters", H),
        ("Michelin", "A tyre brand", "Also rates restaurants", H),
        ("Nintendo", "A gaming brand", "Fun before power", M),
        ("Louis Vuitton", "A fashion brand", "Initials on everything", H),
        ("Heineken", "A drink brand", "A green bottle", H),
        ("Volkswagen", "A car brand", "The people's car", H),
    ]),

    "countries": ("Countries", "\U0001F310", [
        ("Italy", "A European country", "Shaped like footwear", E),
        ("France", "A European country", "Bread and a tower", E),
        ("Japan", "An Asian country", "Islands and order", E),
        ("Brazil", "A South American country", "Football and forest", E),
        ("Egypt", "An African country", "Very old buildings", E),
        ("Australia", "A country and a continent", "Everything bites", E),
        ("Canada", "A North American country", "Polite and cold", E),
        ("Mexico", "A North American country", "Spice and colour", E),
        ("Spain", "A European country", "Late dinners", E),
        ("India", "An Asian country", "Very many people", E),
        ("Germany", "A European country", "Cars and punctuality", E),
        ("China", "An Asian country", "Made most of it", E),
        ("Greece", "A European country", "Ruins and islands", M),
        ("Norway", "A European country", "Long water, short days", M),
        ("Croatia", "A European country", "A long thin coast", M),
        ("Switzerland", "A European country", "Neutral and expensive", M),
        ("Argentina", "A South American country", "Beef and tango", M),
        ("Netherlands", "A European country", "Flat and cycling", M),
        ("South Korea", "An Asian country", "Pop and technology", M),
        ("Turkey", "A country in two continents", "Between two worlds", M),
        ("Iceland", "A European country", "Fire under ice", M),
        ("Portugal", "A European country", "Facing the ocean", M),
        ("Morocco", "An African country", "Markets and mint tea", M),
        ("Thailand", "An Asian country", "Beaches and street food", M),
        ("New Zealand", "A country of islands", "More sheep than people", M),
        ("Kenya", "An African country", "Runners and wildlife", H),
        ("Peru", "A South American country", "High and ancient", H),
        ("Finland", "A European country", "Quiet and steamy", H),
        ("Vietnam", "An Asian country", "Scooters everywhere", H),
        ("Ireland", "A European country", "Green and lyrical", M),
        ("Chile", "A South American country", "Long and narrow", H),
    ]),

    "cities": ("Cities", "\U0001F3D9", [
        ("Paris", "A European city", "Romance and queues", E),
        ("London", "A European city", "Rain and red buses", E),
        ("New York", "An American city", "Never sleeps", E),
        ("Tokyo", "An Asian city", "Enormous and polite", E),
        ("Rome", "A European city", "History underfoot", E),
        ("Barcelona", "A European city", "Unfinished church", E),
        ("Dubai", "A Middle Eastern city", "Newer and taller", E),
        ("Venice", "A European city", "Streets of water", E),
        ("Berlin", "A European city", "A wall that fell", M),
        ("Los Angeles", "An American city", "Traffic and cameras", E),
        ("Sydney", "An Australian city", "Harbour and shells", M),
        ("Amsterdam", "A European city", "Bikes and canals", M),
        ("Istanbul", "A city in two continents", "Two sides, one city", M),
        ("Rio de Janeiro", "A South American city", "Beach and carnival", M),
        ("Moscow", "A European city", "Red square", M),
        ("Prague", "A European city", "Bridges and spires", M),
        ("Las Vegas", "An American city", "Bright and expensive", M),
        ("Cairo", "An African city", "Beside the old triangles", M),
        ("Athens", "A European city", "Ruins on a hill", M),
        ("Lisbon", "A European city", "Tiles and trams", M),
        ("Singapore", "An Asian city", "Clean by law", M),
        ("Hong Kong", "An Asian city", "Vertical living", M),
        ("Vienna", "A European city", "Coffee and composers", M),
        ("Buenos Aires", "A South American city", "Steak and dancing", H),
        ("Cape Town", "An African city", "A flat mountain", H),
        ("Marrakesh", "An African city", "A maze of stalls", H),
        ("Copenhagen", "A European city", "Design and bicycles", H),
        ("Seoul", "An Asian city", "Fast and bright", M),
        ("Dubrovnik", "A European city", "Walls by the sea", H),
        ("Reykjavik", "A European city", "Small and northern", H),
    ]),
}
